dataset_name: S1_Seoul
pre_path: ../../datasets/S1_Seoul/S1_ASCENDING_VH_20220728_Pre.tif
post_path: ../../datasets/S1_Seoul/S1_ASCENDING_VH_20220809_Post.tif
output_dir: ../outputs/S1_Seoul
gt_path: null

align_to_grid: post
nodata_override: null
hist_bins: 256
histogram_quantile_clip: [0.001, 0.999]
min_tile_size: 128
min_valid_pixels_per_tile: 4096
min_valid_ratio_per_tile: 0.5
bm_min_pixels: 4096
std_epsilon: 0.05
ashman_d_threshold: 2.0
bc_threshold: 0.99
sr_threshold: 0.1
seed_tau: 0.01

sigma_rg_step: 0.2
delta_cd_min: 0.0
delta_cd_max: 8.0
delta_cd_step: 0.2
fallback_relaxations: true

rg_connectivity: 8
min_component_pixels: 9

save_selected_tile_details: false
export_full_valid_rasters: true
preview_max_pixels: 2000000
preview_downsample_stride: null

save_intermediate_tifs: true
save_intermediate_pngs: true
verbose_logging: true
