/* GENERATED by tests/sync_gee_probes.py; edit production/helpers or probes/*.js.
 * Copy this entire file to GEE. No Imports or export tasks are required.
 * Local tests do not establish cloud success.
 */
// 只运行所选组；每次改此项重新运行。assets仅只读检查已经完成的small阶段资产。
var PROBE_GROUP = 'quick'; // quick | geometry | topology | prepare | solver | gradient | assets
var PROBE_ASSETS = {assetRoot: '', runId: 'cfdepth_v321_small', step: 2};
// small资产必须由主入口fixture:'small'、其余默认数值参数生成，不在本探针创建任务。
// BEGIN SHARED PRODUCTION CODE
/* CFDepth v3.2.1 — GEE Code Editor, imported getFloodInput() (0/1, invalid pixels masked).
 * Read README.md. Stages: components -> prepare -> iterate -> final.
 * Auto mode submits and waits for stage tasks. Keep this Code Editor page open.
 * Final products ONLY: CFDepth and CFDepth_WSE_Gradient (m/m, not degrees).
 * Numerical convergence does not establish water-depth accuracy.
 */
// 洪水范围：选择 GEE 上方已导入的影像，不填写文件夹路径。
// 按当前 Imports：image 广西；image2 郑州；image3 涿州；image4 美国。
// 只替换括号内的导入变量名，例如 image、image2、image3、image4。
function getFloodInput() {
  return ee.Image(image4);
}
var CONFIG = {
  // 空字符串：自动使用导入影像父目录；也可显式填写已有临时状态目录。
  assetRoot: '',
  runId: 'cfdepth_v321_run01', stage: 'components', step: 1,
  inputRevision: '',             // Required for computed getFloodInput() without asset ID.
  fixture: '',                   // '' / 'small' / 'large'; no imported image for fixtures.
  exportName: 'CFDepth_v3', exportFolder: 'FloodDepth', // 最终产品的 Google Drive 文件夹。
  pairRadius: 2, peerRadius: 3, slopeScaleDeg: 5, sigmaFloor: 0.25,
  dispersionScaleMeters: 1, madScale: 1.4826, minSamplesPerSide: 3,
  highWeight: 0.5, minAnchors: 3, minSpanPixels: 2, minDepth: 0.01,
  lambdaC: 1, lambdaB: 10, lambdaT: 1,
  muRatios: [1e-3, 1e-4, 1e-5, 1e-6],
  sweepsPerStage: 10, maxSweeps: 2000,
  residualTolerance: 0.001, objectiveTolerance: 1e-6, objectiveFloor: 1e-8,
  budgetRelative: 1e-4, budgetAbsolute: 1e-8,
  hardTolerance: 1e-9, monotonicTolerance: 1e-10,
  diagnosticDetails: false, // 显式开启旧加权/含空值去重及详细控制台输出。
  noData: -9999, tileScale: 4, maxPixels: 1e13
};
var VERSION = 'cfdepth-soft-interval-v3.2.1';
// 调度配置独立于数值参数签名；manual保留原stage/step用法。
var RUN_OPTIONS = {mode:'auto', pollSeconds:30, resume:true, cleanupPreviousStates:true};
var EARTH_RADIUS = 6378137;
var STATE_FIELDS = ['status','attempt','sweeps','stable','prev_primary',
  'prev_total','base_primary','base_mid'];
// status: 0 unsupported, 1 primary running, 2 secondary running,
//         3 secondary accepted, 4 primary retained, 5 primary failed.

function numericOps() {
  return {c:function(x){return x;},add:function(a,b){return a+b;},
    sub:function(a,b){return a-b;},mul:function(a,b){return a*b;},div:function(a,b){return a/b;},
    min:Math.min,max:Math.max,abs:Math.abs,lt:function(a,b){return a<b;},
    lte:function(a,b){return a<=b;},gt:function(a,b){return a>b;},eq:function(a,b){return a===b;},
    and:function(a,b){return a&&b;},or:function(a,b){return a||b;},not:function(a){return !a;},
    choose:function(t,a,b){return t?a:b;}};
}

// 固定的地形相容性权重；不是语义概率或统计置信度。
function boundaryTerms(wet,dry,slope,peer,cfg,o) {
  var c=o.c, add=o.add, sub=o.sub, mul=o.mul;
  var square=function(x){return mul(x,x);};
  var down=function(r){return o.div(c(1),add(c(1),square(r)));};
  var ws=o.max(c(cfg.sigmaFloor),mul(c(cfg.madScale),wet.mad));
  var ds=o.max(c(cfg.sigmaFloor),mul(c(cfg.madScale),dry.mad));
  var variance=add(square(ws),square(ds));
  var lower=sub(wet.median,ws),upper=add(dry.median,ds),mid=mul(add(lower,upper),c(0.5));
  var order=sub(wet.median,dry.median);
  // order^2 / sigma^2 avoids needing a scalar/image sqrt adapter.
  var orderWeight=o.div(c(1),add(c(1),o.div(square(o.max(order,c(0))),variance)));
  var weight=o.min(c(1),o.div(o.min(wet.count,dry.count),c(cfg.minSamplesPerSide)));
  weight=mul(weight,mul(down(o.div(slope,c(cfg.slopeScaleDeg))),
    mul(o.div(c(1),add(c(1),o.div(variance,c(cfg.dispersionScaleMeters*cfg.dispersionScaleMeters)))),orderWeight)));
  weight=o.choose(o.lte(lower,upper),weight,c(0));
  if (peer) {
    var ps=o.max(c(cfg.sigmaFloor),mul(c(cfg.madScale),peer.mad));
    var excess=o.max(c(0),sub(o.abs(sub(mid,peer.median)),mul(c(3),ps)));
    var local=down(o.div(excess,add(ws,ds)));
    weight=mul(weight,o.choose(o.lte(c(3),peer.count),local,c(1)));
  }
  return {lower:lower,upper:upper,mid:mid,weight:weight};
}

// 返回有效性和导数分开；缺失方向不会作为已观测到的零梯度。
function directionalDifference(center,plus,minus,dp,dm,hp,hm,o) {
  return {valid:o.or(hp,hm),value:o.choose(o.and(hp,hm),o.div(o.sub(plus,minus),o.add(dp,dm)),
    o.choose(hp,o.div(o.sub(plus,center),dp),o.div(o.sub(center,minus),dm)))};
}

function hasBoundarySupport(count,xmin,xmax,ymin,ymax,cfg,o) {
  return o.and(o.lte(o.c(cfg.minAnchors),count),
    o.lte(o.c(cfg.minSpanPixels),o.max(o.sub(xmax,xmin),o.sub(ymax,ymin))));
}

// 精确求解单像元凸分段二次问题；Node测试和GEE使用同一个数学内核。
// 构建阶段不变的六个区间；不缓存随当前水面变化的邻居和。
function coordinateTemplate(v,o) {
  var z=o.c(0),big=o.c(1e12),regions=[];
  for(var side=-1;side<=1;side++)for(var below=0;below<=1;below++){
    var low=side===1?v.upper:o.sub(z,big),high=side===-1?v.lower:big;
    if(side===0){low=v.lower;high=v.upper;}
    low=o.max(low,below?o.sub(z,big):v.terrain);
    high=o.min(high,below?v.terrain:big);
    low=o.max(low,o.choose(v.hard,v.terrain,o.sub(z,big)));
    var bw=side===0?z:v.boundary,target=side===-1?v.lower:v.upper,tw=below?v.soft:z;
    regions.push({low:low,high:high,feasible:o.lte(low,high),
      denominator:o.max(o.add(o.add(v.degree,bw),o.add(tw,v.midWeight)),o.c(1e-30)),
      boundaryNumerator:o.mul(bw,target),otherNumerator:o.add(o.mul(tw,v.terrain),o.mul(v.midWeight,v.mid))});
  }
  return {v:v,regions:regions,meanDenominator:o.max(v.degree,o.c(1e-30))};
}
function coordinateMinimumFromTemplate(neighborSum,template,o) {
  var v=template.v,z=o.c(0),best=o.c(1e30),answer=z;
  var square=function(x){return o.mul(x,x);};
  var mean=o.div(neighborSum,template.meanDenominator);
  template.regions.forEach(function(r){
    // 保持v3.1分子加法顺序，避免把缓存优化变成数值重排实验。
    var num=o.add(o.add(neighborSum,r.boundaryNumerator),r.otherNumerator);
    var s=o.max(r.low,o.min(r.high,o.div(num,r.denominator)));
    var dist=o.max(z,o.max(o.sub(v.lower,s),o.sub(s,v.upper)));
    var energy=o.add(o.mul(v.degree,square(o.sub(s,mean))),
      o.add(o.mul(v.boundary,square(dist)),o.add(o.mul(v.soft,square(o.max(z,o.sub(v.terrain,s)))),
        o.mul(v.midWeight,square(o.sub(s,v.mid))))));
    var take=o.and(r.feasible,o.lt(energy,best));
    answer=o.choose(take,s,answer);best=o.choose(take,energy,best);
  });
  return answer;
}
function coordinateMinimum(v,o) {
  return coordinateMinimumFromTemplate(v.neighborSum,coordinateTemplate(v,o),o);
}

// 两阶段稳定+坐标残差；次级先验按每个分量的主目标预算接受/减权/回退。
function advanceComponent(s,r,cfg,o) {
  var c=o.c,a=o.add,m=o.mul,sub=o.sub;
  var primary=o.eq(s.status,c(1)),secondary=o.eq(s.status,c(2)),active=o.or(primary,secondary);
  var rel=function(x,y){return o.div(o.abs(sub(x,y)),o.max(o.abs(y),c(cfg.objectiveFloor)));};
  var feasible=o.and(o.eq(r.bad,c(0)),o.lte(r.hard,c(cfg.hardTolerance)));
  var monotone=o.lte(r.total,a(s.prev_total,m(c(cfg.monotonicTolerance),o.max(c(1),o.abs(s.prev_total)))));
  var healthy=o.and(feasible,monotone);
  var steady=o.and(o.lte(rel(r.primary,s.prev_primary),c(cfg.objectiveTolerance)),
    o.lte(rel(r.total,s.prev_total),c(cfg.objectiveTolerance)));
  var stable=o.choose(o.and(steady,healthy),a(s.stable,c(1)),c(0));
  var sweeps=a(s.sweeps,c(cfg.sweepsPerStage));
  var converged=o.and(healthy,o.and(o.lte(r.residual,c(cfg.residualTolerance)),o.lte(c(2),stable)));
  var exhausted=o.lte(c(cfg.maxSweeps),sweeps);
  var baseReady=o.and(primary,converged);
  var baseFailed=o.and(primary,o.and(o.not(converged),o.or(exhausted,o.not(healthy))));
  var budget=o.max(m(c(cfg.budgetRelative),s.base_primary),c(cfg.budgetAbsolute));
  var accepted=o.and(secondary,o.and(converged,o.lte(sub(r.primary,s.base_primary),budget)));
  var rejected=o.and(secondary,o.and(o.not(accepted),o.or(converged,o.or(exhausted,o.not(healthy)))));
  var retry=o.and(rejected,o.lt(a(s.attempt,c(1)),c(cfg.muRatios.length)));
  var fallback=o.and(rejected,o.not(retry)), reset=o.or(baseReady,retry), next={};
  next.status=o.choose(baseReady,c(2),o.choose(baseFailed,c(5),o.choose(accepted,c(3),o.choose(fallback,c(4),s.status))));
  next.attempt=o.choose(baseReady,c(0),o.choose(retry,a(s.attempt,c(1)),s.attempt));
  next.sweeps=o.choose(reset,c(0),o.choose(active,sweeps,s.sweeps));
  next.stable=o.choose(reset,c(0),o.choose(active,stable,s.stable));
  next.base_primary=o.choose(baseReady,r.primary,s.base_primary);
  next.base_mid=o.choose(baseReady,r.mid,s.base_mid);
  var mu=c(0);
  cfg.muRatios.forEach(function(ratio,i){mu=o.choose(o.eq(next.attempt,c(i)),c(cfg.lambdaB*ratio),mu);});
  next.prev_primary=o.choose(reset,next.base_primary,o.choose(active,r.primary,s.prev_primary));
  next.prev_total=o.choose(reset,a(next.base_primary,m(mu,next.base_mid)),o.choose(active,r.total,s.prev_total));
  next.saveBase=baseReady;next.restoreBase=o.or(retry,fallback);
  return next;
}

function validateConfig(cfg) {
  if(cfg.diagnosticDetails!==undefined&&typeof cfg.diagnosticDetails!=='boolean')throw Error('diagnosticDetails must be boolean');
  if (['components','prepare','iterate','final'].indexOf(cfg.stage)<0) throw Error('Unknown stage');
  if (!/^[A-Za-z0-9_-]+$/.test(cfg.runId)) throw Error('Invalid runId');
  if (typeof cfg.assetRoot!=='string')
    throw Error('CONFIG.assetRoot 必须是原生 JavaScript 字符串，空字符串自动选择输入父目录，非空字符串指定临时状态输出目录；导入影像请放在 getFloodInput()，不能使用 ee.Image、ee.String 或列表作为目录');
  if (cfg.assetRoot.indexOf('YOUR_PROJECT')>=0 || /[<>]/.test(cfg.assetRoot))
    throw Error('请将 CONFIG.assetRoot 的占位路径替换为已创建、可写的 GEE 资产文件夹；它不是洪水输入');
  if (cfg.step<0 || cfg.step%1 || (cfg.stage==='iterate' && cfg.step<1)) throw Error('Invalid step');
  if (cfg.sweepsPerStage<1 || cfg.sweepsPerStage%1 || cfg.maxSweeps<2*cfg.sweepsPerStage ||
      cfg.maxSweeps%cfg.sweepsPerStage) throw Error('Invalid sweep schedule');
  ['lambdaC','lambdaB','lambdaT','sigmaFloor','slopeScaleDeg','dispersionScaleMeters',
    'residualTolerance','objectiveTolerance','objectiveFloor','budgetRelative','budgetAbsolute'].forEach(function(k){
    if (!(cfg[k]>0) || !isFinite(cfg[k])) throw Error('Invalid parameter '+k);
  });
  ['pairRadius','peerRadius','minSamplesPerSide','minAnchors','minSpanPixels'].forEach(function(k){
    if (!(cfg[k]>=1)||cfg[k]%1) throw Error('Expected positive integer '+k);
  });
  if (!(cfg.highWeight>0&&cfg.highWeight<=1) || !(cfg.minDepth>=0) || !isFinite(cfg.minDepth))
    throw Error('Invalid boundary weight/depth threshold');
  if (!cfg.muRatios.length) throw Error('At least one secondary attempt is required');
  cfg.muRatios.forEach(function(r,i){if (!(r>0&&r<1)||(i&&r>=cfg.muRatios[i-1])) throw Error('muRatios must decrease in (0,1)');});
  if (!(cfg.noData<0)||cfg.step>99999) throw Error('Invalid NoData/state index');
}

// 只检查客户端输入形态；像元编码仍由真实 GEE 预检检查。
function validateFloodInput(cfg,input) {
  if (cfg.fixture) return;
  if (!input || typeof input.select!=='function' || typeof input.get!=='function')
    throw Error('缺少有效的 getFloodInput()：请选择 GEE Imports 中已导入的影像，例如 image4；不要填写资产路径字符串或文件夹');
}

// 初次准备和恢复使用同一个导入对象的来源，不把影像序列化进参数签名。
function floodSourceToken(input,cfg,assetToken) {
  var sourceId=input.get('system:id').getInfo();
  if (!sourceId&&!cfg.inputRevision) throw Error('Set inputRevision for computed getFloodInput()');
  return sourceId?assetToken(sourceId):cfg.inputRevision;
}

// 延迟读取 Imports：合成场景和 Node 模块加载无需导入；不吞掉其他 GEE 错误。
function resolveFloodInput(cfg) {
  if (cfg.fixture) return null;
  try {
    return getFloodInput();
  } catch (error) {
    if (error && error.name==='ReferenceError')
      throw Error('洪水导入变量未定义：请在顶部 getFloodInput() 的 ee.Image(...) 中填写 GEE Imports 已导入的变量名。原始错误：'+error.message);
    throw error;
  }
}

// 只接受可识别的资产 ID；不将任意路径猜测为用户资产目录。
function checkAssetPath(path,isImage) {
  if (typeof path!=='string' || path!==path.trim() || /\s|[<>]|\/\/|(?:^|\/)\.\.?(?:\/|$)/.test(path))
    throw Error('Invalid GEE asset path: '+path);
  var legacy=path.replace(/^projects\/earthengine-legacy\/assets\//,'');
  var pattern=legacy.indexOf('users/')===0
    ? (isImage?/^users\/[^/]+\/[^/]+(?:\/[^/]+)*$/:/^users\/[^/]+(?:\/[^/]+)*$/)
    : (isImage?/^projects\/[^/]+\/assets\/[^/]+(?:\/[^/]+)*$/:/^projects\/[^/]+\/assets(?:\/[^/]+)*$/);
  if (!pattern.test(legacy)) throw Error('Unrecognized GEE asset path: '+path);
  return path;
}

// 兼容Code Editor与REST的影像、文件夹及影像集合类型枚举。
function requireAssetType(info,path,expected) {
  var actual=info?info.type:undefined;
  var normalized=actual==='Image'||actual==='IMAGE'?'IMAGE':
    actual==='Folder'||actual==='FOLDER'?'FOLDER':
    actual==='ImageCollection'||actual==='IMAGE_COLLECTION'?'IMAGE_COLLECTION':null;
  if (normalized!==expected)
    throw Error('Asset type mismatch: path='+path+', actual='+JSON.stringify(actual===undefined?null:actual)+', expected='+expected);
}

function resolveAssetLocation(cfg,input,getAsset,listAssets) {
  var sourceId=cfg.fixture?null:input.get('system:id').getInfo();
  if (sourceId) {
    checkAssetPath(sourceId,true);
    var source=getAsset(sourceId);
    requireAssetType(source,sourceId,'IMAGE');
  }
  if (!cfg.assetRoot && !sourceId)
    throw Error('无法自动确定目录：合成场景或无资产 ID 的计算影像必须显式设置 CONFIG.assetRoot；inputRevision 不能代替目录');
  var root=cfg.assetRoot || sourceId.slice(0,sourceId.lastIndexOf('/'));
  checkAssetPath(root,false);
  // 项目根目录不是普通文件夹资产；用有界列表请求确认可访问性，空目录也有效。
  if (/^projects\/[^/]+\/assets$/.test(root)) {
    var listing=listAssets(root,{pageSize:1});
    if (!listing || typeof listing!=='object' || Array.isArray(listing) ||
        (listing.assets!==undefined && !Array.isArray(listing.assets)))
      throw Error('Invalid project asset listing: '+root);
  } else {
    requireAssetType(getAsset(root),root,'FOLDER');
  }
  return {root:root,sourceId:sourceId}; // 可读不代表可写；写权限由导出任务验证。
}

function stageAssetPaths(root,cfg) {
  var prefix=root+'/'+cfg.runId;
  return {components:prefix+'_components',prepared:prefix+'_prepared',
    state:function(step){return prefix+'_state_'+('00000'+step).slice(-5);}};
}

function configSignature(cfg) {
  var params={version:VERSION};
  Object.keys(cfg).forEach(function(k){
    if (['stage','step','exportName','exportFolder','assetRoot','runId','diagnosticDetails'].indexOf(k)<0) params[k]=cfg[k];
  });
  return JSON.stringify(params);
}

function requireNewAsset(path,getAsset) {
  var found;
  try {found=getAsset(path);} catch(e){if (!/not found|does not exist/i.test(String(e))) throw e;}
  if (found) throw Error('Refusing existing asset: '+path);
}

// 投影对象的 transform() 是 WKT；仅使用 getInfo() 中的六元素数组。
function validatedGrid(info,context,demGrid) {
  var crs=info&&info.crs,t=info&&info.transform;
  function fail(reason){throw Error(context+': '+reason+'; grid='+JSON.stringify(info));}
  if (typeof crs!=='string'||!crs.trim()) fail('CRS must be a nonempty string');
  if (!Array.isArray(t)||t.length!==6) fail('transform must contain six numbers, not WKT');
  t.forEach(function(v){if(typeof v!=='number'||!isFinite(v)) fail('transform contains a non-finite/non-numeric value');});
  var determinant=t[0]*t[4]-t[1]*t[3];
  if (!isFinite(determinant)||determinant===0) fail('affine matrix is not invertible');
  if (demGrid&&(crs!=='EPSG:4326'||t[1]!==0||t[3]!==0||!(t[0]>0)||!(t[4]<0)))
    fail('FABDEM requires north-up EPSG:4326 without shear');
  return {crs:crs,transform:t.slice()};
}
function gridArguments(info,context,demGrid) {
  var grid=validatedGrid(info,context,demGrid);
  return {crs:grid.crs,crsTransform:grid.transform};
}
function validateInputStats(stats,context) {
  if (!stats||typeof stats!=='object'||Array.isArray(stats)) throw Error(context+': invalid reduction result');
  var count=stats.raw_count,value=stats.raw_max;
  if (count===0||count===null) throw Error(context+': input has no valid pixels');
  if (typeof count!=='number'||!isFinite(count)||count<0||count%1)
    throw Error(context+': invalid valid-pixel count: '+JSON.stringify(stats));
  if (value===1) throw Error(context+': input contains values other than 0/1; NoData must be masked');
  if (value!==0) throw Error(context+': invalid encoding statistic: '+JSON.stringify(stats));
  return count;
}
function validateInputRaster(raw,cfg,eeApi) {
  var context=cfg.stage+' / input flood raster';
  var grid=validatedGrid(raw.projection().getInfo(),context,false);
  var args=gridArguments(grid,context,false);
  args.reducer=eeApi.Reducer.max().combine({reducer2:eeApi.Reducer.count(),sharedInputs:true});
  args.geometry=raw.geometry();args.maxPixels=cfg.maxPixels;args.tileScale=cfg.tileScale;args.bestEffort=false;
  var stats=raw.neq(0).and(raw.neq(1)).reduceRegion(args).getInfo();
  return {grid:grid,validPixels:validateInputStats(stats,context)};
}
// 唯一整数索引入口：坐标可能位于像元中心(半整数)，负索引也必须向下取整。
function pixelIndices(projection,eeApi) {
  return eeApi.Image.pixelCoordinates(projection).floor().toInt64().reproject(projection);
}
function fourColors(indices) {
  return indices.select('x').mod(2).add(2).mod(2)
    .add(indices.select('y').mod(2).add(2).mod(2).multiply(2)).rename('color');
}
// 保存和读取使用同一契约；state只存变化状态，DEM/边界来自独立快照。
function stageBandNames(kind) {
  var components=['dem','cid','support','dry','hard'];
  var state=['S','baseS'].concat(STATE_FIELDS);
  if(kind==='components')return components;
  if(kind==='prepared')return components.concat(['lower','upper','mid','weight','eligible'],state);
  if(kind==='state')return state;
  throw Error('Unknown stage asset kind: '+kind);
}
function packStage(image,kind) {return image.select(stageBandNames(kind)).toDouble();}
function validateStageMetadata(props,cfg,kind,expectedStep,componentToken,preparedToken) {
  stageBandNames(kind);
  if(!props||props.version!==VERSION||props.config_signature!==configSignature(cfg)||
      props.kind!==kind||props.run_id!==cfg.runId)throw Error('Incompatible asset/parameters; rebuild with a new v3.2.1 runId');
  if(componentToken!==undefined&&props.component_token!==componentToken)throw Error('Component snapshot changed');
  if(kind==='state'&&(!preparedToken||props.prepared_token!==preparedToken))throw Error('Prepared snapshot changed');
  if(expectedStep!==undefined&&props.step!==expectedStep)throw Error('Unexpected stage sequence');
}

function validateStageBands(props,bands,kind,context) {
  var grid=validatedGrid({crs:props.grid_crs,transform:props.grid_transform},context+' metadata',true);
  if (!Array.isArray(bands)||!bands.length) throw Error(context+': stage has no bands');
  var required=stageBandNames(kind);
  required.forEach(function(name){
    if (!bands.some(function(b){return b.id===name;})) throw Error(context+': missing band '+name);
  });
  bands.forEach(function(b){
    var actual=validatedGrid({crs:b.crs,transform:b.crs_transform},context+'/'+b.id,true);
    if (actual.crs!==grid.crs||JSON.stringify(actual.transform)!==JSON.stringify(grid.transform))
      throw Error(context+'/'+b.id+': actual grid differs from metadata');
  });
}
// 字符串属性用于持久化；六元素数组只用于计算和实际导出网格。
function stageGridProperties(grid) {
  var checked=validatedGrid(grid,'stage grid serialization',true);
  return {grid_crs:checked.crs,grid_transform_json:JSON.stringify(checked.transform)};
}
function restoreStageProperties(props,bands,cfg,kind,context,expectedStep,components,preparedToken) {
  validateStageMetadata(props,cfg,kind,expectedStep,components?components.component_token:undefined,preparedToken);
  var hasJSON=Object.prototype.hasOwnProperty.call(props,'grid_transform_json');
  var hasArray=Object.prototype.hasOwnProperty.call(props,'grid_transform');
  var transform,legacy;
  function parseGrid(value,label){return validatedGrid({crs:props.grid_crs,transform:value},context+' '+label,true).transform;}
  if(hasJSON){
    if(typeof props.grid_transform_json!=='string')throw Error(context+': grid_transform_json must be a JSON string');
    try{transform=JSON.parse(props.grid_transform_json);}catch(error){throw Error(context+': invalid grid_transform_json JSON');}
    transform=parseGrid(transform,'grid_transform_json');
  }
  if(hasArray){
    legacy=parseGrid(props.grid_transform,'legacy grid_transform');
    if(hasJSON&&JSON.stringify(transform)!==JSON.stringify(legacy))throw Error(context+': conflicting grid transform properties');
    if(!hasJSON)transform=legacy;
  }
  if(!hasJSON&&!hasArray){
    // 仅兼容已核验版本的缺失属性，绝不以实际网格覆盖损坏属性。
    if(props.version!=='cfdepth-soft-interval-v3.2.1')throw Error(context+': missing grid transform properties');
    var anchor=kind==='state'?'S':'dem';
    var band=Array.isArray(bands)&&bands.filter(function(b){return b.id===anchor;})[0];
    if(!band)throw Error(context+': missing band '+anchor+' for grid recovery');
    var actual=validatedGrid({crs:band.crs,transform:band.crs_transform},context+' missing properties / actual '+anchor,true);
    if(props.grid_crs!==actual.crs)throw Error(context+': declared grid_crs differs from actual grid');
    transform=actual.transform;
  }
  var restored={};Object.keys(props).forEach(function(k){restored[k]=props[k];});
  restored.grid_transform=transform.slice();
  validateStageBands(restored,bands,kind,context);
  if(cfg.fixture&&props.source_token!=='synthetic-'+cfg.fixture+'-'+VERSION)throw Error(context+': fixture source changed');
  if(cfg.fixture==='small'&&(props.grid_crs!=='EPSG:4326'||JSON.stringify(transform)!==JSON.stringify([1/3600,0,110,0,-1/3600,30])))
    throw Error(context+': small fixture grid mismatch');
  if(components){
    if(props.grid_crs!==components.grid_crs||JSON.stringify(transform)!==JSON.stringify(components.grid_transform))
      throw Error(context+': stage grid differs from components');
    if(props.source_token!==components.source_token)throw Error(context+': stage source differs from components');
    if(props.region_json!==components.region_json)throw Error(context+': stage region differs from components');
  }
  return restored;
}
// 保留策略只记录客户端资产事实，不参与数值签名或求解。
function autoStageLimit(cfg) {return (1+cfg.muRatios.length)*cfg.maxSweeps/cfg.sweepsPerStage;}
function emptyStateCleanup() {return {through:0,doneThrough:0,pending:[]};}
function autoAssetMissing(error) {
  var message=String(error);
  return /not found|does not exist/i.test(message)&&!/permission|access|forbidden|unauthoriz/i.test(message);
}
function stateRetentionToken(path,info) {
  var revision=info&&(info.updateTime||info.version);
  if(!((typeof revision==='string'&&revision.length)||(typeof revision==='number'&&isFinite(revision)&&revision>0)))
    throw Error('State revision unavailable; refusing retention operation: '+path);
  return JSON.stringify([path,revision,info.sizeBytes||(info.properties||{})['system:asset_size']||null]);
}
function validateRetentionRecord(record,root,cfg) {
  if(!record||record.schema==='cfdepth-auto-1')return;
  if(record.schema!=='cfdepth-auto-2')throw Error('Unknown automation journal schema');
  var latest=record.latestState,cleanup=record.cleanup,paths=stageAssetPaths(root,cfg);
  function check(entry){
    if(!entry||typeof entry.step!=='number'||!isFinite(entry.step)||entry.step<1||entry.step%1||entry.step>autoStageLimit(cfg)||
        entry.path!==paths.state(entry.step)||typeof entry.token!=='string'||!entry.token)
      throw Error('Invalid retained state path/step/token');
  }
  if(latest!==null)check(latest);
  if(!cleanup||!Array.isArray(cleanup.pending)||typeof cleanup.through!=='number'||
      typeof cleanup.doneThrough!=='number'||cleanup.doneThrough<0||cleanup.through<cleanup.doneThrough||
      cleanup.through%1||cleanup.doneThrough%1||!isFinite(cleanup.through)||
      cleanup.through>(latest?latest.step-1:0)||cleanup.pending.length!==cleanup.through-cleanup.doneThrough)
    throw Error('Invalid state cleanup authorization');
  cleanup.pending.forEach(function(entry,i){check(entry);if(entry.step!==cleanup.doneThrough+i+1)throw Error('Non-contiguous cleanup authorization');});
}
function autoInventory(assetIds,root,cfg,record) {
  validateRetentionRecord(record,root,cfg);
  function canonical(path){return path.replace(/^projects\/earthengine-legacy\/assets\//,'');}
  var prefix=canonical(root)+'/'+cfg.runId,found={components:false,prepared:false,steps:[]};
  assetIds.forEach(function(path){var id=canonical(path);
    if(id===prefix+'_components')found.components=true;
    else if(id===prefix+'_prepared')found.prepared=true;
    else if(id.indexOf(prefix+'_state_')===0){
      var tail=id.slice((prefix+'_state_').length);
      if(!/^\d{5}$/.test(tail)||Number(tail)<1||Number(tail)>autoStageLimit(cfg))throw Error('Invalid saved state sequence: '+id);
      found.steps.push(Number(tail));
    }
  });
  found.steps.sort(function(a,b){return a-b;});
  if((found.prepared&&!found.components)||(found.steps.length&&!found.prepared))throw Error('Stage asset gap before prepared');
  var modern=record&&record.schema==='cfdepth-auto-2',cleanup=modern?record.cleanup:emptyStateCleanup();
  var latest=modern&&record.latestState,seen={};
  found.steps.forEach(function(s){
    if(seen[s]||s<=cleanup.doneThrough)throw Error('Duplicate or reappeared deleted state: '+s);
    seen[s]=true;
  });
  var highest=found.steps.length?found.steps[found.steps.length-1]:0;
  if(modern){
    if(latest&&!seen[latest.step])throw Error('Latest retained state is missing: '+latest.path);
    var next=record.current&&record.current.stage==='iterate'?record.current.step:0;
    if(next&&next!==(latest?latest.step:0)+1)throw Error('Current iterate does not follow retained checkpoint');
    if(highest>Math.max(latest?latest.step:0,next))throw Error('Unrecorded future state');
  }
  for(var step=cleanup.through+1;step<=highest;step++)if(!seen[step])throw Error('Stage asset gap at step '+step);
  found.latestStep=highest;
  return found;
}
// 空ImageCollection仅保存调度JSON；旧Folder只读保留。创建与属性写入分开核验。
function createAutomationStore(data,root,cfg,identity) {
  var path=root+'/'+cfg.runId+'_automation_record',legacyPath=root+'/'+cfg.runId+'_automation';
  function guarded(label,fn){try{return fn();}catch(e){throw Error(label+' ['+path+']: '+String(e));}}
  function optional(id){try{return data.getAsset(id);}catch(e){if(autoAssetMissing(e))return null;throw e;}}
  function parse(info,id,type){
    if(!info)return null;
    requireAssetType(info,id,type);
    var props=info.properties||{};
    if(props.automation_json===undefined)return null;
    if(typeof props.automation_json!=='string')throw Error('Invalid automation JSON property: '+id);
    var record=JSON.parse(props.automation_json);
    if(!record||['cfdepth-auto-1','cfdepth-auto-2'].indexOf(record.schema)<0||!record.exports||
        typeof record.identity!=='string'||(identity!==undefined&&record.identity!==identity))
      throw Error('Automation journal identity/schema mismatch: '+id);
    validateRetentionRecord(record,root,cfg);return record;
  }
  function inspect(){return guarded('回读记录',function(){
    var info=optional(path),oldInfo=optional(legacyPath);
    var current=parse(info,path,'IMAGE_COLLECTION'),legacy=parse(oldInfo,legacyPath,'FOLDER');
    var oldJSON=legacy?JSON.stringify(legacy):'',marker=info?(info.properties||{}).legacy_automation_json:undefined;
    // 标记固定迁移时的旧记录，允许新记录正常推进，但旧记录再变化必须停止。
    if(marker!==undefined&&(typeof marker!=='string'||marker!==oldJSON))throw Error('Legacy automation record changed/conflicts');
    if(current&&legacy&&marker===undefined&&JSON.stringify(current)!==oldJSON)
      throw Error('New and legacy automation records conflict');
    if(!current&&marker!==undefined)throw Error('Incomplete automation record with migration marker');
    return {info:info,current:current,legacy:legacy,oldJSON:oldJSON};
  });}
  function write(record){
    var snapshot=inspect(),encoded=JSON.stringify(record);
    if(record.identity!==identity)throw Error('写入记录: automation identity mismatch');
    validateRetentionRecord(record,root,cfg);
    if(!snapshot.info)guarded('创建记录资产',function(){
      data.createAsset({type:'ImageCollection'},path,false);
      requireAssetType(data.getAsset(path),path,'IMAGE_COLLECTION');
    });
    guarded('写入记录',function(){
      data.setAssetProperties(path,{automation_json:encoded,legacy_automation_json:snapshot.oldJSON});
    });
    var confirmed=inspect();
    if(!confirmed.current||JSON.stringify(confirmed.current)!==encoded)
      throw Error('回读记录 ['+path+']: Journal readback mismatch');
  }
  return {path:path,read:function(){var s=inspect();return s.current||s.legacy;},write:write};
}
function validateGrouping(names,methods,context) {
  if (!names.length||names.length!==methods.length) throw Error(context+': grouped reducer arity mismatch');
  var seen={};names.forEach(function(name,i){
    if (name==='cid'||seen[name]||['sum','min','max'].indexOf(methods[i])<0)
      throw Error(context+': invalid grouped reducer field '+name);
    seen[name]=true;
  });
}

// GEE要求weighted输入先于unweighted；排序波段而不改变sum权重语义。
function groupedLayout(names,methods,context) {
  validateGrouping(names,methods,context);
  var fields=names.map(function(name,i){return {name:name,method:methods[i]};});
  fields=fields.filter(function(f){return f.method==='sum';})
    .concat(fields.filter(function(f){return f.method!=='sum';}));
  return {names:fields.map(function(f){return f.name;}),methods:fields.map(function(f){return f.method;})};
}
function buildGroupedReducer(layout,eeApi) {
  var reducer;
  layout.names.forEach(function(name,i){
    var next=eeApi.Reducer[layout.methods[i]]().setOutputs([name]);
    reducer=i===0?next:reducer.combine({reducer2:next,sharedInputs:false});
  });
  return reducer.group({groupField:layout.names.length,groupName:'cid'});
}
// 分量门控只限制成员，不得把统计波段的小数掩膜重置成1。
function groupedInput(image,names,ids,eeApi,projection) {
  var selected=image.select(names);
  var valid=ids.gt(0).and(ids.lt(Math.pow(2,53))).and(ids.mod(1).eq(0));
  // unmask只填零掩膜；用常量底图where生成满掩膜准入图，避免保留cid的小数掩膜。
  var admitted=eeApi.Image.constant(0).toByte().setDefaultProjection(projection).where(valid,1);
  var masked=selected.updateMask(selected.mask().multiply(admitted));
  // cid只提供分组键；其掩膜明确为二值，统计权重仍来自各数据波段。
  var labels=ids.unmask(0,false).updateMask(admitted).rename('cid');
  return masked.addBands(labels);
}
// 缓存按影像对象、偏移和所属网格上下文隔离；动态S不进入这个缓存。
function createStaticShiftCache(at) {
  var sources=[],offsets=[];
  return function(image,dx,dy){
    var index=sources.indexOf(image);
    if(index<0){index=sources.length;sources.push(image);offsets.push({});}
    var key=dx+','+dy;
    if(!Object.prototype.hasOwnProperty.call(offsets[index],key))offsets[index][key]=at(image,dx,dy);
    return offsets[index][key];
  };
}

// 成员检查使用满掩膜0/1指示图；不改写生产support的值或掩膜。
function componentIndicator(image,projection,eeApi) {
  return eeApi.Image.constant(0).toByte().reproject(projection)
    .where(image.unmask(0,false).gt(0),1);
}
function componentReductionArgs(grid,region,cfg,reducer) {
  var args=gridArguments(grid,cfg.stage+' / component audit',true);
  args.geometry=region;args.reducer=reducer;args.maxPixels=cfg.maxPixels;
  args.tileScale=cfg.tileScale;args.bestEffort=false;return args;
}
// 独立核对编号集合及每个有效编号的整数像元数，不通过固定减1修正空值。
function compareComponentIds(vectorIds,histogram) {
  if (!Array.isArray(vectorIds)||!histogram||typeof histogram!=='object'||Array.isArray(histogram))
    throw Error('Invalid component ID set/histogram');
  var known={},raster={},unknown=[],missing=[],pixels=0,nullCount=0;
  function validId(id){return typeof id==='number'&&isFinite(id)&&id>0&&id%1===0&&id<Math.pow(2,53);}
  vectorIds.forEach(function(id){
    if (!validId(id)||known[id]) throw Error('Invalid/duplicate vector component_id: '+id);
    known[id]=true;
  });
  Object.keys(histogram).forEach(function(key){
    var id=Number(key),count=histogram[key];
    if (typeof count!=='number'||!isFinite(count)||count<=0||count%1||count>=Math.pow(2,53))
      throw Error('Invalid component histogram entry: '+key+'='+count);
    // 服务端可能返回null桶；保留原始计数，但它不是有效分量。
    if (key==='null'){nullCount=count;return;}
    if (!validId(id)||raster[id]!==undefined)
      throw Error('Invalid component histogram entry: '+key+'='+count);
    raster[id]=count;pixels+=count;
    if (!known[id]) unknown.push({id:id,pixels:count});
  });
  vectorIds.forEach(function(id){if (raster[id]===undefined) missing.push({id:id,pixels:0});});
  return {missing_ids:missing,unknown_ids:unknown,raster_id_pixels:raster,
    raw_component_histogram:histogram,histogram_null_count:nullCount,
    histogram_distinct_ids:Object.keys(raster).length,histogram_pixels:pixels,
    unknown_id_pixels:unknown.reduce(function(sum,item){return sum+item.pixels;},0)};
}
// 数量相等不足以证明集合相等；逐像元missing/added均必须为零。
function componentAuditError(d) {
  var fields=['expected','restored','missing','added','raw_spill','invalid_ids','vector_count','distinct_ids','histogram_distinct_ids','histogram_pixels','histogram_null_count','unknown_id_pixels'];
  for (var i=0;i<fields.length;i++) {
    var value=d[fields[i]];
    if (typeof value!=='number'||!isFinite(value)||value<0||value%1||value>=Math.pow(2,53))
      return 'Invalid integer component diagnostic: '+fields[i]+'='+value;
  }
  if (!d.expected) return 'Empty flood support';
  if (d.missing||d.added||d.expected!==d.restored) return 'Component rasterization changed pixel membership';
  if (d.invalid_ids||!d.vector_count||d.distinct_ids!==d.vector_count) return 'Invalid or merged component IDs';
  if (!Array.isArray(d.missing_ids)||!Array.isArray(d.unknown_ids)||d.missing_ids.length||d.unknown_ids.length||
      d.unknown_id_pixels||d.histogram_pixels!==d.restored||d.histogram_distinct_ids!==d.distinct_ids)
    return 'Component ID sets or histogram disagree';
  return null;
}
function auditComponentRaster(support,ids,painted,grid,region,cfg,eeApi,vectorIds) {
  var p=eeApi.Projection(grid.crs,grid.transform);
  var expected=componentIndicator(support,p,eeApi).rename('expected');
  var restored=componentIndicator(ids,p,eeApi).rename('restored');
  var raw=componentIndicator(painted,p,eeApi);
  var missing=expected.and(restored.not()).rename('missing');
  var added=restored.and(expected.not()).rename('added');
  var invalid=ids.neq(ids).or(ids.lte(0)).or(ids.gte(Math.pow(2,53))).or(ids.mod(1).neq(0));
  var invalidIds=componentIndicator(invalid,p,eeApi).and(expected).rename('invalid_ids');
  var images=eeApi.Image.cat([expected,restored,missing,added,
    raw.and(expected.not()).rename('raw_spill'),invalidIds]);
  var validIds=ids.updateMask(expected.and(invalid.not())).rename('cid');
  var requests={counts:images.reduceRegion(componentReductionArgs(grid,region,cfg,eeApi.Reducer.sum().unweighted())),
    distinct:validIds.reduceRegion(componentReductionArgs(grid,region,cfg,eeApi.Reducer.countDistinctNonNull().unweighted())).get('cid'),
    histogram:validIds.reduceRegion(componentReductionArgs(grid,region,cfg,eeApi.Reducer.frequencyHistogram().unweighted())).get('cid')};
  if(cfg.diagnosticDetails){
    requests.weighted=eeApi.Image.cat([support.rename('weighted_expected'),ids.gt(0).rename('weighted_restored')])
      .reduceRegion(componentReductionArgs(grid,region,cfg,eeApi.Reducer.sum()));
    requests.includingNull=validIds.reduceRegion(componentReductionArgs(grid,region,cfg,eeApi.Reducer.countDistinct().unweighted())).get('cid');
  }
  // 一次客户端请求获取共同上游的检查；不等同于服务器只执行一次归约。
  var response=eeApi.Dictionary(requests).getInfo(),counts=response.counts,histogram=response.histogram;
  counts.distinct_ids=response.distinct===null?0:response.distinct;
  if(cfg.diagnosticDetails){
    counts.weighted_expected=response.weighted.weighted_expected;counts.weighted_restored=response.weighted.weighted_restored;
    counts.distinct_ids_including_null=response.includingNull===null?0:response.includingNull;
  }
  var sets=compareComponentIds(vectorIds,histogram===null?{}:histogram);
  Object.keys(sets).forEach(function(key){counts[key]=sets[key];});
  var known=ids.remap(vectorIds,vectorIds.map(function(){return 1;}),0);
  var unknownIds=componentIndicator(known.not(),p,eeApi).and(expected).and(invalidIds.not()).rename('unknown_ids');
  return {counts:counts,missing:missing,added:added,invalid:invalidIds,unknown:unknownIds,
    difference:missing.or(added).or(invalidIds).or(unknownIds)};

}
function buildComponentRaster(support,grid,region,cfg,eeApi,report) {
  grid=validatedGrid(grid,cfg.stage+' / component rasterization',true);
  var p=eeApi.Projection(grid.crs,grid.transform),coord=pixelIndices(p,eeApi).toDouble();
  var expected=componentIndicator(support,p,eeApi);
  var extentCheck=eeApi.Dictionary({count:expected.rename('n').reduceRegion(componentReductionArgs(grid,region,cfg,
    eeApi.Reducer.sum().unweighted())).get('n'),extent:coord.updateMask(expected).reduceRegion(componentReductionArgs(grid,region,cfg,
    eeApi.Reducer.minMax().unweighted()))}).getInfo();
  var count=extentCheck.count,ext=extentCheck.extent;
  if (!(count>0)) throw Error('Empty flood support');
  var width=ext.x_max-ext.x_min+1,height=ext.y_max-ext.y_min+1;
  if (!(width>0&&height>0)||width%1||height%1||!isFinite(width*height)||width*height>=Math.pow(2,53))
    throw Error('Component key exceeds exact integer range: '+JSON.stringify(ext));
  var key=coord.select('y').subtract(ext.y_min).multiply(width)
    .add(coord.select('x').subtract(ext.x_min)).add(1).toInt64();
  var args=componentReductionArgs(grid,region,cfg,eeApi.Reducer.min().unweighted().setOutputs(['component_id']));
  args.eightConnected=true;args.geometryType='polygon';args.geometryInNativeProjection=true;args.labelProperty='support_value';
  var vectors=support.selfMask().toInt().addBands(key.rename('pixel_key')).reduceToVectors(args);
  var withId=vectors.filter(eeApi.Filter.notNull(['component_id']));
  var marked=withId.map(function(f){
    var id=eeApi.Number(f.get('component_id'));
    return f.set('invalid_id',id.lte(0).or(id.gte(Math.pow(2,53))).or(id.mod(1).neq(0)));
  });
  var vectorInfo=eeApi.Dictionary({vector_count:vectors.size(),with_id:withId.size(),
    invalid:marked.filter(eeApi.Filter.eq('invalid_id',1)).size(),
    min_id:withId.aggregate_min('component_id'),max_id:withId.aggregate_max('component_id'),
    unique_ids:withId.aggregate_count_distinct('component_id'),component_ids:withId.aggregate_array('component_id')}).getInfo();
  if(cfg.diagnosticDetails)report('Component vector diagnostics:',{grid:grid,expected:count,vectors:vectorInfo});
  if (!vectorInfo.vector_count||vectorInfo.with_id!==vectorInfo.vector_count||vectorInfo.invalid||
      vectorInfo.unique_ids!==vectorInfo.vector_count)
    throw Error('Missing, invalid or duplicate component_id before paint: '+JSON.stringify(vectorInfo));
  // 不裁剪绘制底图以免引入新的边界掩膜；随后仅按原support限定最终编号。
  var painted=eeApi.Image.constant(0).toInt64().reproject(p).paint(vectors,'component_id')
    .reproject(p).rename('cid');
  var ids=painted.updateMask(support).rename('cid');
  var audit=auditComponentRaster(support,ids,painted,grid,region,cfg,eeApi,vectorInfo.component_ids);
  audit.counts.vector_count=vectorInfo.vector_count;
  audit.counts.min_id=vectorInfo.min_id;audit.counts.max_id=vectorInfo.max_id;
  report('Component pixel diagnostics:',cfg.diagnosticDetails||componentAuditError(audit.counts)?{grid:grid,counts:audit.counts}:
    {expected:audit.counts.expected,restored:audit.counts.restored,components:audit.counts.distinct_ids,missing:audit.counts.missing,added:audit.counts.added});
  return {ids:ids,painted:painted,coord:coord,audit:audit,vectors:vectors,grid:grid};
}
// 不导出差异文件；按原网格、相同AOI查找异常，仅打印最多十个候选点。
function showComponentFailure(result,region,cfg,eeApi,map,report) {
  map.addLayer(result.audit.missing.selfMask(),{palette:['FF0000']},'Component missing pixels',false);
  map.addLayer(result.audit.added.selfMask(),{palette:['00FFFF']},'Component added pixels',false);
  map.addLayer(result.audit.invalid.selfMask(),{palette:['FFFF00']},'Component invalid IDs',false);
  map.addLayer(result.audit.unknown.selfMask(),{palette:['FF00FF']},'Component unknown IDs',false);
  report('Missing and unknown component IDs:',{missing:result.audit.counts.missing_ids,unknown:result.audit.counts.unknown_ids});
  var p=eeApi.Projection(result.grid.crs,result.grid.transform);
  var samples=result.coord.rename(['column','row']).addBands(result.ids.unmask(0,false))
    .addBands(result.painted.rename('painted_cid')).updateMask(result.audit.difference);
  // 全分辨率sample，不用随机numPixels（不是严格上限）；limit仅限制打印的记录数。
  var points=samples.sample({region:region,projection:p,tileScale:cfg.tileScale,
    dropNulls:true,geometries:false}).limit(10);
  report('Component mismatch samples (at most 10, original DEM row/column):',points);
}

// 纯栅格运算上下文：不读取资产、不创建任务；正式入口和云端探针共享。
function createGEEGrid(grid,AOI,cfg,ee) {
  grid=validatedGrid(grid,cfg.stage+' / computation grid',true);
  var CRS=grid.crs,T=grid.transform,P=ee.Projection(CRS,T);
  var constants={},indicesCache,colorCache,latitudeCache,distanceCache={};
  function C(x){
    if(typeof x!=='number')return ee.Image.constant(x).toDouble().setDefaultProjection(P).clip(AOI);
    var key=String(x);
    if(!Object.prototype.hasOwnProperty.call(constants,key))constants[key]=ee.Image.constant(x).toDouble().setDefaultProjection(P).clip(AOI);
    return constants[key];
  }
  function imgOps(){
    return {c:C,add:function(a,b){return a.add(b);},sub:function(a,b){return a.subtract(b);},
      mul:function(a,b){return a.multiply(b);},div:function(a,b){return a.divide(b);},
      min:function(a,b){return a.min(b);},max:function(a,b){return a.max(b);},abs:function(a){return a.abs();},
      lt:function(a,b){return a.lt(b);},lte:function(a,b){return a.lte(b);},gt:function(a,b){return a.gt(b);},
      eq:function(a,b){return a.eq(b);},and:function(a,b){return a.and(b);},or:function(a,b){return a.or(b);},
      not:function(a){return a.not();},choose:function(t,a,b){return b.where(t,a);}};
  }
  function numOps(){var o=imgOps();o.c=ee.Number;o.choose=function(t,a,b){return ee.Number(ee.Algorithms.If(t,a,b));};return o;}
  function geometryArgs(reducer){var args=gridArguments({crs:CRS,transform:T},cfg.stage+' / reduction',true);
    args.reducer=reducer;args.geometry=AOI;args.maxPixels=cfg.maxPixels;args.tileScale=cfg.tileScale;args.bestEffort=false;return args;}
  function total(image,reducer){return image.reduceRegion(geometryArgs(reducer));}
  // 平移传递ID，避免卷积或float32舍入；dx/dy表示要读取的邻居偏移。
  function at(image,dx,dy){return image.translate(-dx,-dy,'pixels',P).reproject(P);}
  function finite(image){return image.eq(image).and(image.abs().lt(1e11));}
  function pack(images){return ee.Image.cat(images).setDefaultProjection(P);}
  function xy(){if(!indicesCache)indicesCache=pixelIndices(P,ee);return indicesCache;}
  var dirs=[[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]];
  var staticAt=createStaticShiftCache(at);
  function colors(){if(!colorCache)colorCache=fourColors(xy());return colorCache;}
  function metricDistance(dx,dy){
    var key=dx+','+dy;if(distanceCache[key])return distanceCache[key];
    if(!latitudeCache)latitudeCache=ee.Image.pixelLonLat().select('latitude').reproject(P);
    var lat=latitudeCache;
    var midLat=lat.add(staticAt(lat,dx,dy)).multiply(Math.PI/360);
    var east=midLat.cos().multiply(EARTH_RADIUS*Math.abs(T[0])*Math.PI/180*dx);
    distanceCache[key]=east.pow(2).add(Math.pow(EARTH_RADIUS*Math.abs(T[4])*Math.PI/180*dy,2)).sqrt();
    return distanceCache[key];
  }
  return {P:P,C:C,xy:xy,colors:colors,at:at,staticAt:staticAt,finite:finite,pack:pack,total:total,
    geometryArgs:geometryArgs,metricDistance:metricDistance,dirs:dirs,imgOps:imgOps,numOps:numOps};
}

// 分量阶段的数据变换与回写检查，外层仅负责资产导出。
function buildComponentStage(raw,dem,grid,AOI,cfg,ee,report,onFailure) {
  var g=createGEEGrid(grid,AOI,cfg,ee),P=g.P;
  var observed=raw.mask().unmask(0,false).clip(AOI).reduceResolution({reducer:ee.Reducer.min(),maxPixels:4096,bestEffort:false}).reproject(P).eq(1);
  var flood=raw.eq(1).reduceResolution({reducer:ee.Reducer.max(),maxPixels:4096,bestEffort:false}).reproject(P)
    .unmask(0).gt(0).and(dem.mask()).and(g.finite(dem));
  var dry=observed.and(flood.not()).and(dem.mask()).and(g.finite(dem)).rename('dry');
  var support=flood.rename('support');
  var components=buildComponentRaster(support,grid,AOI,cfg,ee,
    report);
  var ids=components.ids;
  var diagnostic=components.audit.counts,count=diagnostic.expected,distinct=diagnostic.distinct_ids;
  var problem=componentAuditError(diagnostic);
  if (problem) {
    if(onFailure)onFailure(components);
    throw Error(problem+': '+JSON.stringify(diagnostic));
  }
  if (cfg.diagnosticDetails && diagnostic.distinct_ids_including_null!==diagnostic.distinct_ids)
    report('Null-inclusive count differs; non-null IDs and exact ID sets passed:',diagnostic);
  if (cfg.diagnosticDetails && diagnostic.weighted_expected!==diagnostic.weighted_restored)
    report('Weighted totals differ, but exact pixel membership and IDs passed:',diagnostic);
  var hard=support.and(observed).unmask(0).focal_min(1,'square','pixels').and(support).rename('hard');
  return {image:packStage(g.pack([dem,ids.unmask(0),support,dry,hard]),'components'),audit:components};
}

// 每次用固定的components/prepared构建计算器；所有阶段计算可在内存中验收。
function createGEESolver(D,grid,AOI,cfg,ee,preparedInput) {
  var g=createGEEGrid(grid,AOI,cfg,ee),P=g.P,T=grid.transform;
  var C=g.C,at=g.at,finite=g.finite,pack=g.pack,xy=g.xy,dirs=g.dirs;
  var metricDistance=g.metricDistance,imgOps=g.imgOps,numOps=g.numOps,geometryArgs=g.geometryArgs;
  var ids=D.select('cid').updateMask(D.select('support'));
  var idsFilled=ids.unmask(0),dryImage=D.select('dry'),staticAt=g.staticAt;
  function grouped(image,names,methods){
    var layout=groupedLayout(names,methods,cfg.stage+' / component statistics');
    var reducer=buildGroupedReducer(layout,ee);
    var input=groupedInput(image,layout.names,ids,ee,P);
    var list=ee.List(input.reduceRegion(geometryArgs(reducer)).get('groups',ee.List([])));
    return ee.FeatureCollection(list.map(function(row){return ee.Feature(null,ee.Dictionary(row));}));
  }
  function broadcast(table,key,def){return ids.unmask(0).remap(table.aggregate_array('cid'),table.aggregate_array(key),def===undefined?0:def)
    .toDouble().rename(key).setDefaultProjection(P).updateMask(ids.gt(0));}
  var dem=D.select('dem'), support=D.select('support'), hard=D.select('hard');
  var terrain=dem.add(cfg.minDepth), edge=hard.not().and(support);
  var edgeWeights=dirs.map(function(d){
    var same=ids.eq(staticAt(idsFilled,d[0],d[1]));
    var ref=EARTH_RADIUS*Math.abs(T[4])*Math.PI/180;
    return metricDistance(d[0],d[1]).pow(2).pow(-1).multiply(ref*ref*cfg.lambdaC)
      .updateMask(same).unmask(0).updateMask(support);
  });
  var degree=C(0);
  edgeWeights.forEach(function(w){degree=degree.add(w);});
  function samplesStats(samples){
    var collection=ee.ImageCollection.fromImages(samples), median=collection.median().rename('v');
    var deviations=samples.map(function(im){return im.subtract(median).abs().rename('v');});
    return {median:median,count:collection.count().unmask(0),
      mad:ee.ImageCollection.fromImages(deviations).median()};
  }
  var B=preparedInput?preparedInput.select(['lower','upper','mid','weight']):null;
  function prepare() {
    var boundary=support.and(support.unmask(0).focal_min(1,'square','pixels').not());
    var wetSamples=[],drySamples=[];
    for (var dy=-cfg.pairRadius;dy<=cfg.pairRadius;dy++) {
      for (var dx=-cfg.pairRadius;dx<=cfg.pairRadius;dx++) {
        var shifted=staticAt(dem,dx,dy).rename('v');
        wetSamples.push(shifted.updateMask(ids.eq(staticAt(idsFilled,dx,dy))).updateMask(boundary));
        var touches=C(0);
        dirs.forEach(function(d){touches=touches.or(ids.eq(staticAt(idsFilled,dx+d[0],dy+d[1])).unmask(0));});
        drySamples.push(shifted.updateMask(staticAt(dryImage,dx,dy).and(touches)).updateMask(boundary));
      }
    }
    var wet=samplesStats(wetSamples),drySide=samplesStats(drySamples);
    var slope=ee.Terrain.slope(dem);
    var first=boundaryTerms(wet,drySide,slope,null,cfg,imgOps());
    var lower=first.lower,upper=first.upper,mid=first.mid;
    var prelim=first.weight.updateMask(boundary).unmask(0);
    var peers=[];
    for (var py=-cfg.peerRadius;py<=cfg.peerRadius;py++) {
      for (var px=-cfg.peerRadius;px<=cfg.peerRadius;px++) {
        if (px===0&&py===0) continue;
        peers.push(at(mid.updateMask(prelim.gte(cfg.highWeight)),px,py).rename('v')
          .updateMask(ids.eq(staticAt(idsFilled,px,py))).updateMask(boundary));
      }
    }
    var peer=samplesStats(peers);
    // 无参考点时只取消peer项，不取消有效的湿干统计。
    var safePeer={median:peer.median.unmask(0),mad:peer.mad.unmask(0),count:peer.count};
    var weight=boundaryTerms(wet,drySide,slope,safePeer,cfg,imgOps()).weight
      .updateMask(boundary).clamp(0,1).unmask(0).rename('weight');
    B=pack([lower.unmask(0).rename('lower'),upper.unmask(0).rename('upper'),
      mid.unmask(0).rename('mid'),weight]).updateMask(support);
    var high=weight.gte(cfg.highWeight),coords=xy();
    var stats=pack([weight.rename('weight_sum'),weight.multiply(B.select('mid')).rename('weighted_mid'),
      high.rename('anchors'),coords.select('x').where(high.not(),1e12).rename('xmin'),
      coords.select('x').where(high.not(),-1e12).rename('xmax'),
      coords.select('y').where(high.not(),1e12).rename('ymin'),
      coords.select('y').where(high.not(),-1e12).rename('ymax')]);
    var table=grouped(stats,['weight_sum','weighted_mid','anchors','xmin','xmax','ymin','ymax'],
      ['sum','sum','sum','min','max','min','max']).map(function(f){
      var ok=hasBoundarySupport(ee.Number(f.get('anchors')),ee.Number(f.get('xmin')),ee.Number(f.get('xmax')),
        ee.Number(f.get('ymin')),ee.Number(f.get('ymax')),cfg,numOps());
      return f.set({eligible:ok,initial:ee.Number(f.get('weighted_mid')).divide(ee.Number(f.get('weight_sum')).max(1e-30))});
    });
    var eligible=broadcast(table,'eligible'),initial=broadcast(table,'initial');
    initial=initial.where(hard,initial.max(terrain)).where(eligible.not(),0).rename('S');
    var initState={};
    STATE_FIELDS.forEach(function(k){initState[k]=C(0).updateMask(support).rename(k);});
    initState.status=eligible.rename('status');
    var initMetrics=energyImages(initial,C(0));
    var initTable=grouped(initMetrics,['primary','midterm','norm'],['sum','sum','sum']).map(function(f){
      return f.set('initial_objective',ee.Number(f.get('primary')).divide(ee.Number(f.get('norm')).max(1e-30)));});
    initState.prev_primary=broadcast(initTable,'initial_objective').rename('prev_primary');
    initState.prev_total=initState.prev_primary.rename('prev_total');
    var prepared=D.addBands(B).addBands(eligible.rename('eligible')).addBands(initial)
      .addBands(initial.rename('baseS'));
    STATE_FIELDS.forEach(function(k){prepared=prepared.addBands(initState[k]);});
    return {image:packStage(prepared,'prepared'),table:table};
  }
  function muFor(current) {
    var status=current.select('status'),mu=C(0);
    cfg.muRatios.forEach(function(r,i){mu=mu.where(current.select('attempt').eq(i).and(status.eq(2).or(status.eq(3))),cfg.lambdaB*r);});
    return mu;
  }
  function neighborSum(S){
    var sum=C(0);
    dirs.forEach(function(d,i){sum=sum.add(at(S.unmask(0),d[0],d[1]).multiply(edgeWeights[i]).unmask(0));});
    return sum.updateMask(support);
  }
  var templateMu,minimumTemplate;
  function minimum(S,muImage){
    if(!minimumTemplate||templateMu!==muImage){
      templateMu=muImage;
      minimumTemplate=coordinateTemplate({degree:degree,
        boundary:B.select('weight').multiply(cfg.lambdaB),lower:B.select('lower'),upper:B.select('upper'),
        soft:edge.multiply(cfg.lambdaT),terrain:terrain,hard:hard,
        midWeight:B.select('weight').multiply(muImage),mid:B.select('mid')},imgOps());
    }
    return coordinateMinimumFromTemplate(neighborSum(S),minimumTemplate,imgOps()).rename('S').updateMask(support);
  }
  function energyImages(S,muImage){
    var continuity=C(0);
    dirs.forEach(function(d,i){continuity=continuity.add(S.subtract(at(S.unmask(0),d[0],d[1])).pow(2)
      .multiply(edgeWeights[i]).multiply(0.5).unmask(0));});
    var distance=B.select('lower').subtract(S).max(S.subtract(B.select('upper'))).max(0);
    var primary=continuity.add(distance.pow(2).multiply(B.select('weight')).multiply(cfg.lambdaB))
      .add(terrain.subtract(S).max(0).pow(2).multiply(edge).multiply(cfg.lambdaT)).rename('primary');
    var midpoint=S.subtract(B.select('mid')).pow(2).multiply(B.select('weight')).rename('midterm');
    var normalizer=degree.multiply(0.5).add(B.select('weight').multiply(cfg.lambdaB))
      .add(edge.multiply(cfg.lambdaT)).rename('norm');
    return pack([primary,midpoint,normalizer,primary.add(midpoint.multiply(muImage)).rename('total')]).updateMask(support);
  }
  function diagnostics(S,muImage,state){
    var energy=energyImages(S,muImage),optimal=minimum(S,muImage);
    var bad=finite(S).not().or(finite(optimal).not()).or(finite(energy.select('primary')).not())
      .or(finite(energy.select('total')).not()).or(S.mask().unmask(0).not()).unmask(1).and(support);
    var residual=optimal.subtract(S).abs().where(bad,1e12).unmask(1e12).rename('residual');
    var violation=terrain.subtract(S).max(0).multiply(hard).where(bad,1e12).unmask(1e12).rename('hard_violation');
    var im=energy.where(bad,0).unmask(0).addBands(residual).addBands(violation).addBands(bad.rename('bad'))
      .addBands(state.select(STATE_FIELDS));
    var names=['primary','total','midterm','norm','residual','hard_violation','bad'].concat(STATE_FIELDS);
    var methods=['sum','sum','sum','sum','max','max','sum'].concat(STATE_FIELDS.map(function(){return 'min';}));
    return grouped(im,names,methods).map(function(f){
      var normalizer=ee.Number(f.get('norm')).max(1e-30);
      return f.set({primary:ee.Number(f.get('primary')).divide(normalizer),total:ee.Number(f.get('total')).divide(normalizer),
        mid:ee.Number(f.get('midterm')).divide(normalizer),hard:f.get('hard_violation')});
    });
  }

  function sweep(S,mu,active) {
    var colors=g.colors();
    for(var color=0;color<4;color++) S=S.where(active.and(colors.eq(color)),minimum(S,mu)).rename('S');
    return S;
  }
  function iterate(current) {
    var status=current.select('status'),mu=muFor(current);
    var S=current.select('S'),active=status.eq(1).or(status.eq(2));
    for(var scan=0;scan<cfg.sweepsPerStage;scan++)S=sweep(S,mu,active);
    var checked=diagnostics(S,mu,current);
    var nextTable=checked.map(function(f){
      var s={},r={};STATE_FIELDS.forEach(function(k){s[k]=ee.Number(f.get(k));});
      ['primary','total','mid','residual','hard','bad'].forEach(function(k){r[k]=ee.Number(f.get(k));});
      return f.set(advanceComponent(s,r,cfg,numOps()));
    });
    var baseS=current.select('baseS').where(broadcast(nextTable,'saveBase'),S).rename('baseS');
    S=S.where(broadcast(nextTable,'restoreBase'),baseS).rename('S');
    var next=pack([S,baseS]);
    STATE_FIELDS.forEach(function(k){next=next.addBands(broadcast(nextTable,k));});
    return {image:packStage(next,'state'),table:nextTable};
  }
  function gradientImages(surface,valid) {
    function derivative(dx,dy){
      var plus=at(surface,dx,dy),minus=at(surface,-dx,-dy);
      var hp=plus.mask().unmask(0).gt(0),hm=minus.mask().unmask(0).gt(0);
      var dp=metricDistance(dx,dy),dm=metricDistance(-dx,-dy);
      var result=directionalDifference(surface,plus.unmask(0),minus.unmask(0),dp,dm,hp,hm,imgOps());
      return result.value.updateMask(valid.and(result.valid)).rename('v');
    }
    var gx=derivative(1,0),gy=derivative(0,1);
    var hasX=gx.mask().unmask(0).gt(0),hasY=gy.mask().unmask(0).gt(0);
    // sum忽略masked方向，而不是把缺失导数记录成0。单方向输出仅为可观测幅值。
    var gradient=ee.ImageCollection.fromImages([gx.pow(2),gy.pow(2)]).sum().sqrt()
      .updateMask(valid.and(hasX.or(hasY))).rename('CFDepth_WSE_Gradient').setDefaultProjection(P);
    return {gradient:gradient,gx:gx,gy:gy,hasX:hasX,hasY:hasY};
  }
  function finalize(current) {
    if(!preparedInput)throw Error('Final products require prepared snapshot');
    var prepared=preparedInput,status=current.select('status'),mu=muFor(current);
    var S=current.select('S'),audit=diagnostics(S,mu,current);
    var accepted=status.eq(3).or(status.eq(4));
    var audited=audit.map(function(f){
      var st=ee.Number(f.get('status')),isAccepted=st.eq(3).or(st.eq(4));
      var budget=ee.Number(f.get('base_primary')).multiply(cfg.budgetRelative).max(cfg.budgetAbsolute);
      var ok=ee.Number(f.get('bad')).eq(0).and(ee.Number(f.get('hard')).lte(cfg.hardTolerance))
        .and(ee.Number(f.get('residual')).lte(cfg.residualTolerance))
        .and(ee.Number(f.get('primary')).subtract(f.get('base_primary')).lte(budget));
      return f.set('audit_failed',isAccepted.and(ok.not()));
    });
    var checks=ee.Dictionary({running:audit.filter(ee.Filter.inList('status',[1,2])).size(),
      failed:audited.filter(ee.Filter.eq('audit_failed',1)).size()}).getInfo();
    if(checks.running)throw Error('Unfinished components: '+checks.running+'. Continue iterate; no final export created.');
    if(checks.failed)throw Error('Final residual/constraint/budget audit failed');
    var depth=S.subtract(dem),valid=accepted.and(prepared.select('eligible')).and(finite(S)).and(depth.gt(cfg.minDepth));
    var finalDepth=depth.updateMask(valid).rename('CFDepth');
    var result=gradientImages(S.updateMask(valid),valid);
    result.depth=finalDepth;result.valid=valid;result.audit=audited;
    return result;
  }
  return {prepare:prepare,iterate:iterate,finalize:finalize,sweep:sweep,minimum:minimum,
    energyImages:energyImages,diagnostics:diagnostics,gradientImages:gradientImages,
    grouped:grouped,broadcast:broadcast,muFor:muFor,grid:g};
}

// END SHARED PRODUCTION CODE
var grid={crs:'EPSG:4326',transform:[1/3600,0,110,0,-1/3600,30]};
var cfg={stage:'components-probe',maxPixels:1e7,tileScale:4,diagnosticDetails:true};
var p=ee.Projection(grid.crs,grid.transform),xy=pixelIndices(p,ee);
function regionAt(a){var t=grid.transform;
  return ee.Geometry.Rectangle([t[2]+a[0]*t[0],t[5]+a[3]*t[4],t[2]+a[2]*t[0],t[5]+a[1]*t[4]],grid.crs,false);
}
// 独立JavaScript BFS构造预期八连通编号，不调用生产矢量化或paint。
function reference(values,n){
  var labels=values.map(function(){return 0;}),minX=n,minY=n,maxX=-1,maxY=-1,groups=0;
  values.forEach(function(v,k){if(v){minX=Math.min(minX,k%n);maxX=Math.max(maxX,k%n);
    minY=Math.min(minY,Math.floor(k/n));maxY=Math.max(maxY,Math.floor(k/n));}});
  var width=maxX-minX+1;
  values.forEach(function(v,start){if(!v||labels[start])return;
    groups++;var queue=[start],members=[],minimum=Infinity;labels[start]=-1;
    for(var cursor=0;cursor<queue.length;cursor++){
      var k=queue[cursor],x=k%n,y=Math.floor(k/n);members.push(k);
      minimum=Math.min(minimum,(y-minY)*width+x-minX+1);
      for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++){
        var nx=x+dx,ny=y+dy,next=ny*n+nx;
        if(nx>=0&&nx<n&&ny>=0&&ny<n&&values[next]&&!labels[next]){labels[next]=-1;queue.push(next);}
      }
    }
    members.forEach(function(k){labels[k]=minimum;});
  });return {labels:labels,groups:groups};
}
function verify(name,support,expected,region,groups){
  var result=buildComponentRaster(support,grid,region,cfg,ee,function(m,v){print(name+' '+m,v);});
  var problem=componentAuditError(result.audit.counts);
  if(problem){showComponentFailure(result,region,cfg,ee,Map,print);throw Error(name+': '+problem);}
  var mismatch=componentIndicator(result.ids.unmask(0,false).neq(expected),p,ee);
  var errors=mismatch.rename('mismatch').reduceRegion(componentReductionArgs(grid,region,cfg,
    ee.Reducer.sum().unweighted())).get('mismatch').getInfo();
  if(errors!==0||result.audit.counts.vector_count!==groups)
    throw Error(name+': independent BFS/analytic component labels differ: '+errors);
  print('PASS '+name+': exact support AND independent component labels',result.audit.counts);
}
function small(name,n,fn,aoi){
  var values=[],keys=[];for(var k=0;k<n*n;k++){keys.push(k);values.push(fn(k%n,Math.floor(k/n))?1:0);}
  var ref=reference(values,n),region=regionAt(aoi||[0,0,n,n]);
  var key=xy.select('y').multiply(n).add(xy.select('x'));
  var inside=xy.select('x').gte(0).and(xy.select('x').lt(n)).and(xy.select('y').gte(0)).and(xy.select('y').lt(n));
  var support=key.remap(keys,values,0).where(inside.not(),0).rename('support').reproject(p).clip(region);
  var expected=key.remap(keys,ref.labels,0).where(inside.not(),0).reproject(p);
  verify(name,support,expected,region,ref.groups);
}
// 对全部12个网格位置做独立核对；不通过直方图或生产成员指示图验证自身。
function validateNullProbeSamples(features,labels){
  if (!Array.isArray(features)||features.length!==12)return 'Expected 12 sampled grid positions';
  var seen={},valid=0;
  for(var i=0;i<features.length;i++){
    var a=features[i].properties||{},x=a.column,y=a.row,key=x+','+y;
    if(typeof x!=='number'||typeof y!=='number'||x%1||y%1||x<0||x>=6||y<0||y>=2||seen[key])
      return 'Unexpected or duplicate grid coordinate: '+key;
    seen[key]=true;var wet=y===0&&x<5,expectedId=wet?labels[x]:0;
    if(!(a.support_mask>0)||a.support!==(wet?1:0)||!(a.painted_mask>0)||a.painted_cid!==expectedId)
      return 'Support or painted ID mismatch at '+key;
    if(wet){
      if(!(a.cid_mask>0)||a.cid!==expectedId)return 'Missing or wrong valid ID at '+key;
      valid++;
    }else if(a.cid_mask!==0||(a.cid!==null&&a.cid!==undefined))return 'Background ID is not masked at '+key;
  }
  return valid===5?null:'Expected five supported IDs';
}
function nullCountProbe(){
  var region=regionAt([0,0,6,2]),x=xy.select('x'),y=xy.select('y');
  var support=x.gte(0).and(x.lt(5)).and(y.eq(0)).rename('support').reproject(p).clip(region);
  var labels=[210,220,230,240,502049];
  var painted=x.remap([0,1,2,3,4],labels,0).where(y.neq(0),0).rename('cid').reproject(p);
  var ids=painted.updateMask(support).reproject(p);
  var sampleImage=xy.rename(['column','row'])
    .addBands(ee.Image.pixelCoordinates(p).rename(['raw_x','raw_y'])).addBands(support)
    .addBands(support.mask().rename('support_mask'))
    .addBands(painted.rename('painted_cid')).addBands(painted.mask().rename('painted_mask'))
    .addBands(ids).addBands(ids.mask().rename('cid_mask'));
  var samples=sampleImage.sample({region:region,projection:p,dropNulls:false,geometries:false,tileScale:cfg.tileScale});
  var sampleInfo=samples.getInfo();
  var inputProblem=validateNullProbeSamples(sampleInfo.features,labels);
  print('Null probe input grid and independent sample check:',{grid:grid,error:inputProblem});
  if(inputProblem){
    print('Null probe all grid positions, including masked values:',samples);
    throw Error('Null probe input failed: '+inputProblem);
  }
  var audit=auditComponentRaster(support,ids,painted,grid,region,cfg,ee,labels);
  audit.counts.vector_count=labels.length;
  var problem=componentAuditError(audit.counts);
  print('GEE null-count comparison (ordinary vs non-null):',audit.counts);
  var eachOnce=labels.every(function(id){return audit.counts.raster_id_pixels[id]===1;});
  if(problem||audit.counts.expected!==5||audit.counts.restored!==5||audit.counts.distinct_ids!==5||!eachOnce){
    print('Null probe all grid positions, including masked values:',samples);
    throw Error('Null-count probe failed: '+(problem||'Expected five supported IDs, each occurring once'));
  }
  // 普通计数仅作观测，不强制所有GEE后端均必须计入null；正式条件始终为非空计数及集合一致。
  print('PASS five valid IDs plus masked background');
}
function probe(crs,t) {
  var p=ee.Projection(crs,t),coords=pixelIndices(p,ee);
  function world(x,y){return [t[0]*x+t[1]*y+t[2],t[3]*x+t[4]*y+t[5]];}
  var region=ee.Geometry.Polygon([[world(0,0),world(4,0),world(4,4),world(0,4),world(0,0)]],crs,false);
  var x=coords.select('x'),y=coords.select('y');
  var valid=x.gte(0).and(x.lt(4)).and(y.gte(0)).and(y.lt(4)).and(x.eq(0).and(y.eq(0)).not());
  var raw=x.mod(2).rename('raw').updateMask(valid).reproject(p).clip(region);
  var cfg={stage:'projection-probe',maxPixels:1000,tileScale:1};
  print('WKT diagnostic only (never passed as crsTransform):',p.transform());
  var result=validateInputRaster(raw,cfg,ee);
  if(result.validPixels!==15)throw Error('Expected 15 valid pixels, got '+result.validPixels);
  try {validateInputRaster(raw.where(x.eq(1).and(y.eq(1)),2),cfg,ee);throw Error('Invalid encoding was accepted');}
  catch(e){if(String(e).indexOf('other than 0/1')<0)throw e;}
  try {validateInputRaster(raw.updateMask(ee.Image(0)),cfg,ee);throw Error('Empty input was accepted');}
  catch(e){if(String(e).indexOf('no valid pixels')<0)throw e;}
  print('PASS projection, binary values and NoData:',result);
}
// 汇总独立检查；服务端异常记FAIL，依赖失败记SKIP，不以未执行冒充成功。
var acceptanceResults=[],acceptanceStatus={},acceptanceCache={};
var probeGroups={
  quick:['coordinates_geographic','coordinates_projected','coordinates_rotated','mixed_reducers','null_and_five_ids'],
  geometry:['coordinates_geographic','coordinates_projected','coordinates_rotated','physical_centers_geographic','physical_centers_projected','physical_centers_rotated','projection_and_binary_geographic','projection_and_binary_projected','projection_and_binary_rotated'],
  topology:['coordinates_geographic','topology_non_aligned','topology_hole','topology_diagonal_singleton','topology_independent','topology_small_fixture','relative_component_ids'],
  prepare:['coordinates_geographic','null_and_five_ids','production_components','production_prepare_and_groups'],
  solver:['coordinates_geographic','four_colors_and_neighbors','compact_solver_input','non_equilibrium_real_sweep','compact_state_and_rejection'],
  gradient:['coordinates_geographic','analytic_gradients_and_masks'],
  assets:['saved_stage_contracts']
};
if(!probeGroups[PROBE_GROUP])throw Error('Unknown PROBE_GROUP: '+PROBE_GROUP);

function assertProbe(ok,message){if(!ok)throw Error(message);}
function runCheck(name,dependencies,body){
  if(probeGroups[PROBE_GROUP].indexOf(name)<0){
    acceptanceStatus[name]='NOT_RUN';acceptanceResults.push({name:name,status:'NOT_RUN',elapsed_ms:0});return;
  }
  var started=Date.now();
  var blocked=dependencies.filter(function(key){return acceptanceStatus[key]!=='PASS';});
  if(blocked.length){
    acceptanceStatus[name]='SKIP';acceptanceResults.push({name:name,status:'SKIP',elapsed_ms:0,reason:'Blocked by '+blocked.join(', ')});
    print('SKIP '+name,blocked);return;
  }
  try{body();acceptanceStatus[name]='PASS';acceptanceResults.push({name:name,status:'PASS',elapsed_ms:Date.now()-started});print('PASS '+name);}
  catch(error){var message=String(error);acceptanceStatus[name]='FAIL';acceptanceResults.push({name:name,status:'FAIL',elapsed_ms:Date.now()-started,reason:message});print('FAIL '+name,message);}
}
function maxValue(image,g){return g.total(image.rename('v'),ee.Reducer.max().unweighted()).get('v').getInfo();}
function pixelCount(mask,g){return g.total(componentIndicator(mask,g.P,ee).rename('n'),ee.Reducer.sum().unweighted()).get('n').getInfo();}
function nearValue(actual,expected,tolerance,message){assertProbe(typeof actual==='number'&&isFinite(actual)&&Math.abs(actual-expected)<=tolerance,message+': '+actual+' vs '+expected);}
function validatePacked(image,kind,grid){
  var info=packStage(image,kind).getInfo();
  validateStageBands({grid_crs:grid.crs,grid_transform:grid.transform},info.bands,kind,'acceptance '+kind);
  assertProbe(info.bands.length===stageBandNames(kind).length,'Unexpected saved band count');
}
// 几何变换只服务于物理中心检查，不作为整数索引检查的隐含前置条件。
function coordinateSamples(crs,t,includeWorld){
  var projection=ee.Projection(crs,t),raw=ee.Image.pixelCoordinates(projection),indices=pixelIndices(projection,ee);
  function world(x,y){return [t[0]*x+t[1]*y+t[2],t[3]*x+t[4]*y+t[5]];}
  var region=ee.Geometry.Polygon([[world(-2,-2),world(2,-2),world(2,2),world(-2,2),world(-2,-2)]],crs,false);
  var samples=indices.rename(['column','row']).addBands(raw.rename(['raw_x','raw_y']))
    .sample({region:region,projection:projection,geometries:includeWorld,dropNulls:false});
  if(includeWorld){
    // 少量采样点使用合法的零误差；不改变生产区域的几何误差或求解容差。
    samples=samples.map(function(f){return f.set('world',
      f.geometry().transform(crs,ee.ErrorMargin(0,'meters')).coordinates());});
  }
  return samples.getInfo().features;
}
function validateCoordinateIndices(samples){
  assertProbe(Array.isArray(samples)&&samples.length===16,'Expected 16 positive/negative coordinate samples');
  var seen={};
  samples.forEach(function(f){
    var a=f.properties,x=a.column,y=a.row,key=x+','+y;
    assertProbe(typeof x==='number'&&typeof y==='number'&&x%1===0&&y%1===0&&x>=-2&&x<2&&y>=-2&&y<2&&!seen[key],'Invalid integer indices '+key);
    seen[key]=true;
    assertProbe(typeof a.raw_x==='number'&&isFinite(a.raw_x)&&typeof a.raw_y==='number'&&isFinite(a.raw_y)&&
      x===Math.floor(a.raw_x)&&y===Math.floor(a.raw_y),'Wrong center-to-index conversion');
  });
}
function coordinateIndexProbe(crs,t){
  var samples=coordinateSamples(crs,t,false);
  validateCoordinateIndices(samples);
  print('Coordinates: 16 index samples passed',CONFIG.diagnosticDetails?samples:crs);
}
function coordinateCenterProbe(crs,t){
  var samples=coordinateSamples(crs,t,true);
  validateCoordinateIndices(samples);
  samples.forEach(function(f){
    var a=f.properties,x=a.column+0.5,y=a.row+0.5;
    var expected=[t[0]*x+t[1]*y+t[2],t[3]*x+t[4]*y+t[5]];
    var tol=Math.max(Math.abs(t[0])+Math.abs(t[1]),Math.abs(t[3])+Math.abs(t[4]))*1e-5;
    assertProbe(Array.isArray(a.world)&&a.world.length===2,'Missing physical point coordinates');
    nearValue(a.world[0],expected[0],tol,'Physical pixel center x');nearValue(a.world[1],expected[1],tol,'Physical pixel center y');
  });
  print('Coordinates: 16 physical centers passed',CONFIG.diagnosticDetails?samples:crs);
}
function summarizeAcceptance(results){
  var totals={total:results.length,passed:0,failed:0,skipped:0,not_run:0};
  results.forEach(function(r){
    if(r.status==='PASS')totals.passed++;
    else if(r.status==='FAIL')totals.failed++;
    else if(r.status==='SKIP')totals.skipped++;
    else if(r.status==='NOT_RUN')totals.not_run++;
    else throw Error('Unknown acceptance status: '+r.status);
  });
  return totals;
}
// sum保留原区域权重；极值参考检查所有有原始掩膜的相交像元。
function reducerReferenceBounds(bounds,method){
  return method==='sum'?bounds.slice():[Math.floor(bounds[0]),Math.floor(bounds[1]),Math.ceil(bounds[2]),Math.ceil(bounds[3])];
}
function mixedReducerProbe(){
  var names=['a','peak','b','floor'],methods=['sum','max','sum','min'],requests={};
  var definitions=[{key:'aligned',bounds:[0,0,4,2],groups:[1,2]},
    {key:'non_aligned',bounds:[.2,.2,3.2,2.2],groups:[1]}];
  definitions.forEach(function(def){
    var region=regionAt(def.bounds),g=createGEEGrid(grid,region,CONFIG,ee),x=g.xy().select('x'),y=g.xy().select('y');
    var ids=g.C(1).rename('cid'),mask=g.C(1).where(x.eq(1),.4);
    if(def.key==='aligned'){
      ids=ids.where(x.eq(2),2).where(x.eq(3),0);
      mask=mask.where(x.eq(0).and(y.eq(1)),0);
    }
    var support=ids.gt(0).rename('support');
    var D=g.pack([g.C(0).rename('dem'),ids,support,g.C(0).rename('dry'),support.rename('hard')]);
    var im=g.pack([x.add(1).rename('a'),x.multiply(10).add(7).rename('peak'),
      x.add(2).multiply(3).rename('b'),x.subtract(8).rename('floor')]).updateMask(mask);
    var solver=createGEESolver(D,grid,region,CONFIG,ee),reference={};
    def.groups.forEach(function(id){
      reference[id]={};
      // 非对齐单分量保留原参考输入；两分量用where清零其他成员的原掩膜，独立于生产helper。
      var ref=def.key==='non_aligned'?im:im.updateMask(im.mask().where(ids.neq(id).unmask(1,false),0));
      names.forEach(function(n,i){
        var args=g.geometryArgs(ee.Reducer[methods[i]]());
        if(methods[i]!=='sum')args.geometry=regionAt(reducerReferenceBounds(def.bounds,methods[i]));
        reference[id][n]=ref.select(n).reduceRegion(args).get(n);
      });
    });
    var sorted=groupedLayout(names,methods,'probe'),input=groupedInput(im,sorted.names,ids,ee,g.P);
    var sample=g.xy().rename(['column','row']).addBands(ids.rename('source_cid').unmask(0,false))
      .addBands(im.mask().rename(names.map(function(n){return n+'_before';})))
      .addBands(input.select(names).mask().rename(names.map(function(n){return n+'_after';})))
      .addBands(input.select('cid').mask().rename('cid_mask'))
      // 用GEE实际编码的0.4掩膜作对照，避免JS双精度字面量与服务端掩膜表示差异。
      .addBands(ee.Image.constant(1).updateMask(ee.Image.constant(.4)).mask().rename('fraction_control'));
    requests[def.key]={grouped:solver.grouped(im,names,methods).toList(10),reference:reference,
      samples:sample.sample({region:region,projection:g.P,dropNulls:false,geometries:false}).toList(20),
      legacy_a:g.total(im.select('a').updateMask(ids.gt(0)),ee.Reducer.sum()).get('a')};
    if(def.key==='non_aligned'){
      // 第4列与区域相交但中心在外；第5列完全在外。只读取这两个诊断像元。
      var boundarySample=g.xy().rename(['column','row'])
        .addBands(im.select('peak').unmask(0,false))
        .addBands(im.select('peak').mask().rename('original_mask'))
        .addBands(input.select('peak').mask().rename('filtered_mask'));
      requests[def.key].boundary_samples=boundarySample.sample({region:regionAt([3,0,5,1]),
        projection:g.P,dropNulls:false,geometries:false}).toList(3);
    }
  });
  // 所有字段及像元先一次取回并打印，再汇总断言，不在首个字段失败时隐藏后续结果。
  var results=ee.Dictionary(requests).getInfo(),errors=[];
  print('Mixed reducers: all fields, original/filtered masks and legacy a (diagnostic only)',results);
  function equal(a,b,message){if(typeof a!=='number'||typeof b!=='number'||!isFinite(a)||!isFinite(b)||Math.abs(a-b)>1e-9)errors.push(message+': '+a+' vs '+b);}
  definitions.forEach(function(def){
    var result=results[def.key],seen={};
    result.grouped.forEach(function(f){var row=f.properties,id=row.cid;
      if(seen[id]||def.groups.indexOf(id)<0){errors.push(def.key+' unexpected/duplicate cid '+id);return;}seen[id]=true;
      names.forEach(function(n){equal(row[n],result.reference[id][n],def.key+' cid='+id+' field='+n);});
      if(def.key==='aligned'){
        var analytic=id===1?{peak:17,floor:-8}:{peak:27,floor:-6};
        ['peak','floor'].forEach(function(n){equal(row[n],analytic[n],'Aligned analytic '+id+' '+n);});
      }
    });
    def.groups.forEach(function(id){if(!seen[id])errors.push(def.key+' missing cid '+id);});
    if(def.key==='non_aligned'){
      var boundary=result.boundary_samples||[],boundarySeen={};
      if(boundary.length!==2)errors.push('Expected two boundary diagnostic pixels');
      boundary.forEach(function(f){var a=f.properties,key=a.column+','+a.row;
        if(boundarySeen[key]||a.row!==0||[3,4].indexOf(a.column)<0){errors.push('Invalid boundary coordinate '+key);return;}
        boundarySeen[key]=true;
        if(a.column===3){
          equal(a.peak,37,'Intersecting boundary peak');
          if(!(a.original_mask>0))errors.push('Intersecting boundary lost original mask');
          equal(a.filtered_mask,a.original_mask,'Boundary fractional mask');
          equal(result.reference[1].peak,a.peak,'Reference must include intersecting boundary');
        }else{
          equal(a.original_mask,0,'Exterior original mask');equal(a.filtered_mask,0,'Exterior filtered mask');
        }
      });
      if(!boundarySeen['3,0']||!boundarySeen['4,0'])errors.push('Missing boundary/exterior sample');
    }
    var expectedCount=def.key==='aligned'?8:6,positions={};
    // 非对齐区域按像元中心采样，不能用加权覆盖的12个交叠像元数作为样本数。
    if(result.samples.length!==expectedCount)errors.push(def.key+' sample count '+result.samples.length+' vs '+expectedCount);
    result.samples.forEach(function(f){var a=f.properties,key=a.column+','+a.row;
      if(positions[key])errors.push(def.key+' duplicate sample '+key);positions[key]=true;
      var admitted=a.source_cid>0;
      names.forEach(function(n){equal(a[n+'_after'],admitted?a[n+'_before']:0,def.key+' mask '+key+' '+n);});
      equal(a.cid_mask,admitted?1:0,def.key+' cid gate '+key);
      if(def.key==='aligned'){
        if(!(a.fraction_control>0&&a.fraction_control<1))errors.push('Invalid fractional mask control');
        var expected=a.column===0&&a.row===1?0:a.column===1?a.fraction_control:1;
        names.forEach(function(n){equal(a[n+'_before'],expected,'Aligned original mask '+key+' '+n);});
      }
    });
  });
  if(errors.length)throw Error('Mixed reducer/mask checks failed: '+errors.join('; '));
  print('PASS fractional masks, component isolation and all mixed reducer fields');
}
runCheck('coordinates_geographic',[],function(){coordinateIndexProbe('EPSG:4326',grid.transform);});
runCheck('coordinates_projected',[],function(){coordinateIndexProbe('EPSG:3857',[10,0,1918543,0,-10,7241630]);});
runCheck('coordinates_rotated',[],function(){coordinateIndexProbe('EPSG:3857',[10,2,1918543,1,-10,7241630]);});
runCheck('physical_centers_geographic',['coordinates_geographic'],function(){coordinateCenterProbe('EPSG:4326',grid.transform);});
runCheck('physical_centers_projected',['coordinates_projected'],function(){coordinateCenterProbe('EPSG:3857',[10,0,1918543,0,-10,7241630]);});
runCheck('physical_centers_rotated',['coordinates_rotated'],function(){coordinateCenterProbe('EPSG:3857',[10,2,1918543,1,-10,7241630]);});
runCheck('projection_and_binary_geographic',['coordinates_geographic'],function(){probe('EPSG:4326',grid.transform);});
runCheck('projection_and_binary_projected',['coordinates_projected'],function(){probe('EPSG:3857',[9.32480563590904,0,1918543.3940000013,0,-9.324805635909165,7241630.245534113]);});
runCheck('projection_and_binary_rotated',['coordinates_rotated'],function(){probe('EPSG:3857',[10,2,1918543,1,-10,7241630]);});
runCheck('mixed_reducers',[],mixedReducerProbe);
runCheck('null_and_five_ids',['coordinates_geographic'],nullCountProbe);
runCheck('topology_non_aligned',['coordinates_geographic'],function(){small('non-grid-aligned boundary',6,function(x,y){return x<4&&y<4;},[0.2,0.2,5.2,5.2]);});
runCheck('topology_hole',['coordinates_geographic'],function(){small('hole',9,function(x,y){return x>0&&x<8&&y>0&&y<8&&!(x>=3&&x<=5&&y>=3&&y<=5);});});
runCheck('topology_diagonal_singleton',['coordinates_geographic'],function(){small('diagonal and singleton',8,function(x,y){return (x===1&&y===1)||(x===2&&y===2)||(x===6&&y===6);});});
runCheck('topology_independent',['coordinates_geographic'],function(){small('one pixel gap',9,function(x,y){return y>=2&&y<=6&&((x>=1&&x<=3)||(x>=5&&x<=7));});});
runCheck('topology_small_fixture',['coordinates_geographic'],function(){
  small('existing small fixture topology',36,function(x,y){return (x>=4&&x<24&&y>=4&&y<24&&!(x===14&&y===14))||
    (x>=25&&x<29&&y>=25&&y<29)||(x===27&&y===32)||(x===28&&y===33)||(x===34&&y===34);});
});
runCheck('relative_component_ids',['coordinates_geographic'],function(){
  // 原始坐标的统一中心偏移应在减去最小值时抵消；与整数索引生成的ID逐像元比较。
  var region=regionAt([-2,-2,3,3]),raw=ee.Image.pixelCoordinates(p),idx=pixelIndices(p,ee);
  var ext=raw.reduceRegion({reducer:ee.Reducer.minMax().unweighted(),geometry:region,crs:grid.crs,crsTransform:grid.transform,maxPixels:100});
  var rawKey=raw.select('y').subtract(ee.Number(ext.get('y_min'))).multiply(5)
    .add(raw.select('x').subtract(ee.Number(ext.get('x_min')))).add(1);
  var key=idx.select('y').add(2).multiply(5).add(idx.select('x').add(2)).add(1);
  nearValue(rawKey.subtract(key).abs().reduceRegion({reducer:ee.Reducer.max().unweighted(),geometry:region,crs:grid.crs,crsTransform:grid.transform,maxPixels:100}).values().get(0).getInfo(),0,0,'Relative component ID changed');
});
runCheck('four_colors_and_neighbors',['coordinates_geographic'],function(){
  var region=regionAt([-4,-4,4,4]),g=createGEEGrid(grid,region,CONFIG,ee),idx=g.xy(),colors=fourColors(idx);
  var memberships=g.C(0);for(var k=0;k<4;k++)memberships=memberships.add(colors.eq(k));
  nearValue(maxValue(memberships.neq(1),g),0,0,'Some pixels are assigned no/multiple colors');
  nearValue(maxValue(colors.mod(1).neq(0).or(colors.lt(0)).or(colors.gt(3)),g),0,0,'Colors outside integer 0..3');
  g.dirs.forEach(function(d){nearValue(maxValue(colors.eq(g.at(colors,d[0],d[1])),g),0,0,'Adjacent pixels share a color');});
  nearValue(maxValue(g.at(idx.select('x'),1,0).subtract(idx.select('x').add(1)).abs(),g),0,0,'Horizontal neighbor direction');
  nearValue(maxValue(g.at(idx.select('y'),0,1).subtract(idx.select('y').add(1)).abs(),g),0,0,'Vertical neighbor direction');
});
runCheck('production_components',['coordinates_geographic','null_and_five_ids'],function(){
  var localCfg={};Object.keys(CONFIG).forEach(function(k){localCfg[k]=CONFIG[k];});
  // 只缩短探针扫描阶段，不改变正式CONFIG/资产参数。
  localCfg.sweepsPerStage=1;localCfg.maxPixels=1e6;localCfg.stage='components';
  var region=regionAt([0,0,32,16]),g=createGEEGrid(grid,region,localCfg,ee),ij=g.xy(),x=ij.select('x'),y=ij.select('y');
  var patchA=x.gte(4).and(x.lt(10)).and(y.gte(4)).and(y.lt(10));
  var patchB=x.gte(20).and(x.lt(26)).and(y.gte(4)).and(y.lt(10));
  var isolated=x.eq(28).and(y.eq(12)),support=patchA.or(patchB).or(isolated).reproject(g.P).clip(region);
  var raw=support.toByte().rename('raw'),dem=g.C(100).where(support,99).rename('dem');
  var built=buildComponentStage(raw,dem,grid,region,localCfg,ee,print);
  nearValue(built.audit.audit.counts.expected,73,0,'Production support count');
  nearValue(built.audit.audit.counts.distinct_ids,3,0,'Production component count');
  validatePacked(built.image,'components',grid);
  acceptanceCache={cfg:localCfg,region:region,g:g,D:built.image,patchA:patchA,patchB:patchB,isolated:isolated};
});
runCheck('production_prepare_and_groups',['production_components'],function(){
  var a=acceptanceCache,solver=createGEESolver(a.D,grid,a.region,a.cfg,ee),result=solver.prepare();
  validatePacked(result.image,'prepared',grid);
  var S=result.image.select('S');
  a.prepared=result.image;a.solver=createGEESolver(a.D,grid,a.region,a.cfg,ee,a.prepared);
  var table=a.solver.grouped(a.D.select('support').rename('n'),['n'],['sum']);
  var broadcast=a.solver.broadcast(table,'n');
  var checks=ee.Dictionary({rows:result.table.toList(3),
    initial_error:a.g.total(S.updateMask(a.patchA.or(a.patchB)).subtract(99.5).abs().rename('v'),ee.Reducer.max()).get('v'),
    eligible_pixels:a.g.total(componentIndicator(result.image.select('eligible'),a.g.P,ee).rename('n'),ee.Reducer.sum().unweighted()).get('n'),
    broadcast_error:a.g.total(broadcast.updateMask(a.patchA.or(a.patchB)).subtract(36).abs().rename('v'),ee.Reducer.max()).get('v')}).getInfo();
  var rows=checks.rows;assertProbe(rows.length===3,'Preparation omitted a component');
  var eligible=0;rows.forEach(function(f){var r=f.properties;
    ['cid','anchors','initial','weight_sum','weighted_mid'].forEach(function(key){assertProbe(typeof r[key]==='number'&&isFinite(r[key]),'Non-finite group field '+key);});
    if(r.eligible)eligible++;
  });
  assertProbe(eligible===2,'Two patches should be eligible; singleton must be unsupported');
  nearValue(checks.initial_error,0,1e-8,'Prepared midpoint initial WSE');
  nearValue(checks.eligible_pixels,72,0,'Eligible pixels');
  nearValue(checks.broadcast_error,0,1e-8,'Grouped count/broadcast');
});
// 显式小图仅验证扫描/诊断，不展开生产prepare和多阶段求解；prepare另组独立验收。
runCheck('compact_solver_input',['coordinates_geographic'],function(){
  var cfg={};Object.keys(CONFIG).forEach(function(k){cfg[k]=CONFIG[k];});
  var region=regionAt([0,0,12,6]),g=createGEEGrid(grid,region,cfg,ee),x=g.xy().select('x'),y=g.xy().select('y');
  var patchA=x.gte(1).and(x.lt(4)).and(y.gte(1)).and(y.lt(5));
  var patchB=x.gte(7).and(x.lt(10)).and(y.gte(1)).and(y.lt(5));
  var support=patchA.or(patchB).clip(region),ids=patchA.add(patchB.multiply(2)).rename('cid');
  var D=packStage(g.pack([g.C(99).rename('dem'),ids,support.rename('support'),support.not().rename('dry'),support.rename('hard')]),'components');
  var prepared=D.addBands(g.pack([g.C(99.25).rename('lower'),g.C(100).rename('upper'),g.C(99.5).rename('mid'),g.C(.8).rename('weight'),support.rename('eligible'),g.C(99.5).rename('S'),g.C(99.5).rename('baseS')]));
  STATE_FIELDS.forEach(function(k){prepared=prepared.addBands(g.C(k==='status'?1:0).rename(k));});
  prepared=packStage(prepared.updateMask(support),'prepared');
  acceptanceCache={cfg:cfg,region:region,g:g,D:D,patchA:patchA,patchB:patchB,prepared:prepared,
    solver:createGEESolver(D,grid,region,cfg,ee,prepared)};
  validatePacked(prepared,'prepared',grid);
});
runCheck('non_equilibrium_real_sweep',['compact_solver_input','four_colors_and_neighbors'],function(){
  var a=acceptanceCache,g=a.g,S=a.prepared.select('S');
  var perturbed=S.add(fourColors(g.xy()).eq(0).and(a.patchA).multiply(0.2));
  var active=a.prepared.select('eligible'),next=a.solver.sweep(perturbed,g.C(0),active);
  var checked=ee.Dictionary({
    changed:g.total(next.subtract(perturbed).abs().rename('v'),ee.Reducer.max()).get('v'),
    before:g.total(a.solver.energyImages(perturbed,g.C(0)).select('primary'),ee.Reducer.sum()).get('primary'),
    after:g.total(a.solver.energyImages(next,g.C(0)).select('primary'),ee.Reducer.sum()).get('primary'),
    hard:g.total(a.D.select('dem').add(CONFIG.minDepth).subtract(next).max(0).updateMask(a.D.select('hard')).rename('v'),ee.Reducer.max()).get('v'),
    independent:g.total(next.subtract(S).abs().updateMask(a.patchB).rename('v'),ee.Reducer.max()).get('v')}).getInfo();
  assertProbe(checked.changed>1e-6,'Solver did not update non-equilibrium input');
  assertProbe(isFinite(checked.before)&&isFinite(checked.after)&&checked.after<checked.before,'One real sweep did not reduce the primary objective');
  nearValue(checked.hard,0,1e-9,'Hard lower bound');nearValue(checked.independent,0,1e-8,'Independent component changed');
  print('Real sweep checks',checked);
});
runCheck('compact_state_and_rejection',['compact_solver_input'],function(){
  var a=acceptanceCache,state=packStage(a.prepared,'state');validatePacked(state,'state',grid);
  var rows=a.solver.diagnostics(state.select('S'),a.g.C(0),state).getInfo().features;
  assertProbe(rows.length===2,'Compact diagnostics lost a component');
  rows.forEach(function(f){nearValue(f.properties.bad,0,0,'Non-finite state');nearValue(f.properties.residual,0,1e-8,'Analytic residual');});
  var rejected=false;
  try{a.solver.finalize(state);}catch(e){if(String(e).indexOf('Unfinished components')<0)throw e;rejected=true;}
  assertProbe(rejected,'Unfinished states were allowed to publish');
  var unsupported=state.addBands(a.g.C(0).rename('status'),null,true);
  nearValue(pixelCount(a.solver.finalize(unsupported).valid,a.g),0,0,'Unsupported state published');
});
runCheck('analytic_gradients_and_masks',['coordinates_geographic'],function(){
  // 梯度使用实际生产距离和差分路径，期望值从独立中心几何距离计算。
  [0,60].forEach(function(latitude){
    var gr={crs:'EPSG:4326',transform:[1/3600,0,110,0,-1/3600,latitude]},pp=ee.Projection(gr.crs,gr.transform);
    var region=ee.Geometry.Rectangle([110,latitude-8/3600,110+8/3600,latitude],gr.crs,false);
    var g=createGEEGrid(gr,region,CONFIG,ee),ij=g.xy(),x=ij.select('x'),y=ij.select('y');
    var valid=x.gte(1).and(x.lt(7)).and(y.gte(1)).and(y.lt(7)).clip(region);
    var D=packStage(g.pack([g.C(0).rename('dem'),valid.rename('cid'),valid.rename('support'),valid.not().rename('dry'),valid.rename('hard')]),'components');
    var solver=createGEESolver(D,gr,region,CONFIG,ee),plane=x.multiply(2).add(y.multiply(3)).toDouble().updateMask(valid);
    var result=solver.gradientImages(plane,valid);
    nearValue(pixelCount(result.gradient.mask(),g),36,0,'Planar gradient coverage');
    nearValue(pixelCount(result.hasX.and(result.hasY).and(valid),g),36,0,'Planar two-direction coverage');
    var lat=ee.Image.pixelLonLat().select('latitude').reproject(pp).multiply(Math.PI/180);
    var dx=lat.cos().multiply(EARTH_RADIUS*Math.PI/180/3600),dy=EARTH_RADIUS*Math.PI/180/3600;
    var expected=dx.pow(-1).multiply(2).pow(2).add(Math.pow(3/dy,2)).sqrt();
    nearValue(maxValue(result.gradient.subtract(expected).abs(),g),0,1e-9,'Planar WSE magnitude including one-sided edges');
    var row=x.gte(1).and(x.lt(7)).and(y.eq(2)).clip(region);
    var line=solver.gradientImages(plane.updateMask(row),row);
    nearValue(pixelCount(line.hasX.and(line.hasY).and(row),g),0,0,'One-row surface has two observed directions');
    nearValue(pixelCount(line.gradient.mask(),g),6,0,'One-row gradient coverage');
    nearValue(maxValue(line.gradient.subtract(dx.pow(-1).multiply(2)).abs(),g),0,1e-9,'One-direction gradient');
    var single=x.eq(2).and(y.eq(2)).clip(region),isolated=solver.gradientImages(plane.updateMask(single),single);
    nearValue(pixelCount(isolated.gradient.mask(),g),0,0,'Isolated pixel has a gradient');
  });
});
runCheck('saved_stage_contracts',[],function(){
  var cfg={};Object.keys(CONFIG).forEach(function(k){cfg[k]=CONFIG[k];});
  cfg.assetRoot=PROBE_ASSETS.assetRoot;cfg.runId=PROBE_ASSETS.runId;cfg.fixture='small';
  cfg.step=PROBE_ASSETS.step;cfg.stage='final';validateConfig(cfg);
  assertProbe(cfg.assetRoot&&cfg.step>=2,'assets requires explicit root and saved step >=2');
  var paths=stageAssetPaths(cfg.assetRoot,cfg),metadata={};
  function token(path){if(!metadata[path])metadata[path]=ee.data.getAsset(path);var m=metadata[path];return JSON.stringify([path,m.updateTime||m.startTime||'',m.sizeBytes||'']);}
  var loaded=[];
  [[paths.components,'components',undefined],[paths.prepared,'prepared',0],[paths.state(cfg.step),'state',cfg.step]].forEach(function(item){
    var image=ee.Image(item[0]),info=image.getInfo(),props=info.properties;
    var components=loaded.length?loaded[0].props:undefined;
    if(components)components.component_token=token(paths.components);
    props=restoreStageProperties(props,info.bands,cfg,item[1],item[0],item[2],components,item[1]==='state'?token(paths.prepared):undefined);
    assertProbe(props.source_token==='synthetic-small-'+VERSION,'Unexpected synthetic source');
    if(loaded.length)assertProbe(JSON.stringify(props.grid_transform)===JSON.stringify(loaded[0].props.grid_transform)&&props.grid_crs===loaded[0].props.grid_crs&&props.region_json===loaded[0].props.region_json,'Stage grid/region mismatch');
    loaded.push({image:image,props:props});
  });
  var props=loaded[0].props,gr=validatedGrid({crs:props.grid_crs,transform:props.grid_transform},'assets',true),region=ee.Geometry(JSON.parse(props.region_json));
  var solver=createGEESolver(loaded[0].image,gr,region,cfg,ee,loaded[1].image),state=loaded[2].image;
  var invalidState=state.neq(state).or(state.abs().gte(1e11)).reduce(ee.Reducer.max())
    .or(state.mask().reduce(ee.Reducer.min()).eq(0)).unmask(1).updateMask(loaded[0].image.select('support'));
  var observed=ee.Dictionary({rows:solver.diagnostics(state.select('S'),solver.muFor(state),state).toList(5),
    invalid:solver.grid.total(invalidState.rename('v'),ee.Reducer.max()).get('v')}).getInfo();
  nearValue(observed.invalid,0,0,'Masked/non-finite saved state');
  var rows=observed.rows;
  assertProbe(rows.length===4,'Saved small fixture requires four components');
  rows.forEach(function(f){STATE_FIELDS.forEach(function(k){assertProbe(typeof f.properties[k]==='number'&&isFinite(f.properties[k]),'Invalid state field '+k);});assertProbe(f.properties.bad===0&&typeof f.properties.status==='number'&&f.properties.status%1===0&&f.properties.status>=0&&f.properties.status<=5,'Invalid saved state');});
  print('Saved state diagnostics (no iteration or export)',rows);
  if(rows.some(function(f){return f.properties.status===1||f.properties.status===2;})){
    print('Contracts passed; solution still running. Continue stages in main entry. Final products NOT yet validated.');
  }else{
    var result=solver.finalize(state),g=solver.grid;
    nearValue(pixelCount(result.valid,g),415,0,'Saved fixture final support');
    nearValue(maxValue(result.depth.subtract(.5).abs(),g),0,1e-7,'Saved fixture depth');
    nearValue(maxValue(result.gradient.abs(),g),0,1e-10,'Saved fixture flat gradient');
    print('Final products from saved state passed; no tasks created.');
  }
  // 自动调度记录可选；验收入口只读取，绝不启动任务或更新记录。
  var journal=createAutomationStore(ee.data,cfg.assetRoot,cfg).read();
  if(journal){
    assertProbe(['cfdepth-auto-1','cfdepth-auto-2'].indexOf(journal.schema)>=0,'Unknown automation journal');
    var identity=JSON.parse(journal.identity);
    assertProbe(identity.version===VERSION&&identity.signature===configSignature(cfg)&&identity.runId===cfg.runId&&
      identity.source==='synthetic-small-'+VERSION&&identity.root===cfg.assetRoot,'Automation journal source/config mismatch');
    validateRetentionRecord(journal,cfg.assetRoot,cfg);
    if(journal.schema==='cfdepth-auto-2'){
      assertProbe(journal.latestState&&journal.latestState.step===cfg.step,'Set PROBE_ASSETS.step to journal.latestState.step');
      assertProbe(journal.latestState.token===stateRetentionToken(paths.state(cfg.step),ee.data.getAsset(paths.state(cfg.step))),
        'Latest retained state token mismatch');
    }
    var assetIds=[],page;
    do{
      var listing=ee.data.listAssets(cfg.assetRoot,{pageSize:1000,pageToken:page});
      (listing.assets||[]).forEach(function(a){assetIds.push(a.id||a.name);});page=listing.nextPageToken;
    }while(page);
    autoInventory(assetIds,cfg.assetRoot,cfg,journal);
    if(journal.schema==='cfdepth-auto-2')journal.cleanup.pending.forEach(function(entry){
      var info;try{info=ee.data.getAsset(entry.path);}catch(error){if(autoAssetMissing(error))return;throw error;}
      assertProbe(entry.token===stateRetentionToken(entry.path,info),'Pending old state token mismatch');
      var raster=ee.Image(entry.path).getInfo();
      restoreStageProperties(raster.properties,raster.bands,cfg,'state','pending cleanup probe',entry.step,
        loaded[0].props,token(paths.prepared));
    });
    print('Automation journal (read only):',journal);
    if(journal.complete){
      assertProbe(!journal.current&&journal.exports.depth&&journal.exports.gradient,'Missing completed export receipts');
      var tasks=ee.data.getTaskStatus([journal.exports.depth.id,journal.exports.gradient.id]);
      assertProbe(tasks.length===2&&tasks.every(function(t){return t.state==='COMPLETED';}),'Final export task history not confirmed');
      print('Both automatic export tasks COMPLETED; downloaded GeoTIFFs still require product inspection.');
    }
  }
});
print('CFDepth v3.2.1 selected-group summary (no asset tasks):',acceptanceResults);
var acceptanceTotals=summarizeAcceptance(acceptanceResults);
print('CFDepth group / totals / timing includes client, network and server wait:',PROBE_GROUP,acceptanceTotals);
if(acceptanceTotals.failed||acceptanceTotals.skipped)throw Error('CFDepth acceptance incomplete: '+
  acceptanceTotals.passed+' PASS, '+acceptanceTotals.failed+' FAIL, '+acceptanceTotals.skipped+' SKIP; inspect selected group.');
print('PASS GROUP '+PROBE_GROUP+'. Other groups, asset persistence and large-scene execution remain separate gates.');
