"""确定性同步可直接复制的 GEE 探针；--check 仅核对，不改写。"""
from pathlib import Path
import argparse

BASE = Path(__file__).resolve().parent

def render() -> dict[str, str]:
    source = (BASE.parent / 'CFDepth_0919.txt').read_text()
    # 含纯计算及定义，不包含生产runGEE/自动执行/Export语句。
    shared = source[:source.index('function runGEE(')]
    def case(name: str) -> str:
        return (BASE / 'probes' / name).read_text()
    header = ('/* GENERATED by tests/sync_gee_probes.py; edit production/helpers or probes/*.js.\n'
              ' * Copy this entire file to GEE. No Imports or export tasks are required.\n'
              ' * Local tests do not establish cloud success.\n */\n')
    return {
        'gee_acceptance_probe.js': header + case('acceptance_config.js') + '// BEGIN SHARED PRODUCTION CODE\n' + shared + '// END SHARED PRODUCTION CODE\n' + case('components_cases.js') + case('projection_cases.js') + case('acceptance_cases.js'),
    }

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, text in render().items():
        path = BASE / name
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise SystemExit(f'Stale generated GEE probe: {path}')
        else:
            path.write_text(text)
    print('GEE probes synchronized' if not args.check else 'GEE shared code equality passed')

if __name__ == '__main__':
    main()
